### ISSUE TITLE
Unable to open

### ISSUE THREAD

**Issue by naveen1hot** [elgatito/plugin.video.elementum#716] opened 2021-03-13 03:22 UTC
While opening in android 10 getting error of 
![Screenshot_20210313-084349](https://user-images.githubusercontent.com/67212860/111017340-e39fb000-83d8-11eb-9d39-9b5d85117690.jpg)
'deomon error permission error (13, permission denied). 
Request to fix the issue.
Elementum version 0.1.71
Kodi version 19.0

But the same above version working in Amazon firestick without any error. I'm facing the problem in mobile only. Kindly do the needful.

**Comment by antonsoroko** [comment] 2021-03-13 09:28
right above the "New issue" button

![image](https://user-images.githubusercontent.com/17964763/111025779-6e8fa300-83f7-11eb-9065-4bc054217f32.png)

**Comment by elgatito** [comment] 2021-03-13 12:32
Duplicate of #669

**Closed by elgatito** 2021-03-13 12:32 UTC
