### ISSUE TITLE
Subtitles won't download

### ISSUE THREAD

**Issue by Jwaarsenburg** [elgatito/plugin.video.elementum#282] opened 2018-11-30 21:16 UTC
Good evening all,

After fixing lots of problems, I hope this is the final one.

When I open the subtitle tab, there is a list of subtitles I can choose from.
After selecting one I get the message the downloading failed.
What's going wrong?

https://paste.kodi.tv/adekaxexez.kodi

**Comment by elgatito** [comment] 2018-12-02 20:08
Please, try version 0.0.66. 
There are some changes to searching episodes and shows.

**Comment by Jwaarsenburg** [comment] 2018-12-02 20:57
Alright I will try soon, can I manually update by selecting the addon in Kodi?

**Comment by martinstz** [comment] 2018-12-03 06:37
The problem with subtitles is that Kodi not support WinRAR 5 version, only version 3. And if subtitles are archivated with highest than version 3, Kodi cannot extract them.

**Comment by elgatito** [comment] 2018-12-03 07:00
Not sure there is something to help with. We get subtitles from Opensubtitles, download the file and give it to Kodi.

**Comment by martinstz** [comment] 2018-12-03 07:04
May be he use other subtitles source, like subsunacs and subssab for bulgarian subtitles, where subtitles are archived.

**Comment by Jwaarsenburg** [comment] 2018-12-03 11:34
No I use opensubtitles to download Dutch subtitles

**Comment by elgatito** [comment] 2018-12-03 11:40
@Jwaarsenburg try the latest version of Elementum.

**Comment by Jwaarsenburg** [comment] 2018-12-03 11:53
updated, still doesn't work. This time I use a older movie with English subs... https://paste.kodi.tv/lanuliwudi.kodi

**Comment by elgatito** [comment] 2018-12-03 17:35
Strange error. Your system could not download this subtitles file: https://dl.opensubtitles.org/en/download/src-api/vrf-19c60c5b/sid-MfFtSPelKXUtohqTyId8Aq5ycC0/file/1955186249.gz

I can download it. Do you have any firewall or something?

**Comment by vonhutuan** [comment] 2018-12-08 05:55
I also have the same problem with v0.6.6, on Kodi 18 RC2, Android TV. I was downloading english sub for Venom movie from opensubtitles

**Comment by frozentrone** [comment] 2018-12-10 16:13
I'm having the similar problem. Downloading from "Elementum" subtitle service gives error. I installed OpenSubtitles addon and it works just fine.

**Comment by elgatito** [comment] 2018-12-10 18:06
@vonhutuan @frozentrone would be much helpful if someone shares log file and not just write something that cannot be reproduced.

http://elementum.surge.sh/contribute/log/

**Comment by elgatito** [comment] 2018-12-11 08:38
@Jwaarsenburg @martinstz @vonhutuan @frozentrone If you want this to be fixed - I need log files that show what happens on your system.
I open movie/episode, open subtitles tab, in providers I open "Elementum", then I get list of found subtitles, select any and it's done, I see subtitles.

**Comment by frozentrone** [comment] 2018-12-11 10:35
@elgatito I'll get the log file when I get a chance. Thanks!

**Comment by gabiruh** [comment] 2018-12-15 12:02
Kodi 18 (Leia) removed support for RAR files from base system, now it has a separate addon for dealing with RAR files. You need to look for it in AddOns menu and install it (sorry, I can't remember which section it is located)

**Comment by elgatito** [comment] 2018-12-17 09:40
> Kodi 18 (Leia) removed support for RAR files from base system, now it has a separate addon for dealing with RAR files. 

@gabiruh  There is still no evidence about this case. The only log shows Kodi was not able to download file (which I can download). And I have Kodi 18 and subtitles gets downloaded well by Elementum, because elementum is un-zipping it, before giving to Kodi.

I can't reproduce why file was not unable to download. Maybe it's firewall or something, now allowing to download archive, don't know. 

There is no response in this issue, and if noone answers - I will close it.

**Comment by Jwaarsenburg** [comment] 2018-12-17 17:04
I am not able to test it right now, because I'm away for a few weeks. I will try again when I come back and share my log. If you want to close it in the meanwhile, I'll make a new one later.

**Comment by frozentrone** [comment] 2018-12-17 21:05
The issue somehow resolved on its own after I selected a path for download.

**Comment by antonsoroko** [comment] 2018-12-28 11:47
>The issue somehow resolved on its own after I selected a path for download.


this is because elementum saves subtitles into `Subtitles` directory inside the `download` directory so it should exist and be writable

**Comment by elgatito** [comment] 2018-12-28 12:17
```
	subtitlesPath := filepath.Join(config.Get().DownloadPath, "Subtitles")
	if _, errStat := os.Stat(subtitlesPath); os.IsNotExist(errStat) {
		if errMk := os.Mkdir(subtitlesPath, 0755); errMk != nil {
			subLog.Error("Unable to create Subtitles folder")
		}
	}

```

Ir is created if needed.

**Comment by antonsoroko** [comment] 2018-12-28 12:21
i meant that **download** directory should exist and be writable (like the code says). thanks.

**Comment by elgatito** [comment] 2019-01-01 13:19
Please, use v0.0.71.
Even with non-set directory subtitles download should work.

**Comment by elgatito** [comment] 2019-03-23 20:25
Closing, as got no updates.

**Comment by KillerJoeBR** [comment] 2019-04-07 12:46
So any possible solution? I have set a download path in the settings. Even set a torrent path. 

Could you see anything in the log file that could help? 

Thanks

**Comment by elgatito** [comment] 2019-04-07 12:57
@KillerJoeBR I have no idea why it does not work for you:

```
2019-04-07 07:35:59.109 T:31773  NOTICE: [plugin.video.elementum] [GIN] 2019/04/07 - 10:35:59 | 200 |  1.006493385s |       127.0.0.1 | GET      /subtitle/1956270196?action=download&dl=https%3a%2f%2fdl.opensubtitles.org%2fen%2fdownload%2fsrc-api%2fvrf-19ba0c57%2fsid-k4aQAxOdBDfr8tJyHqlNvSm-C%2c3%2ffile%2f1956270196.gz&file=Bumblebee.2018.1080p.BluRay.x264-SPARKS.srt&fmt=srt&lang=pob&doresume=false
2019-04-07 07:35:59.123 T:32715   DEBUG: onExecutionDone(38, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/navigation.py)
2019-04-07 07:35:59.124 T:32584   ERROR: OnDownloadComplete - Saving of subtitle /storage/emulated/0/Download/Subtitles/Bumblebee.2018.1080p.BluRay.x264-SPARKS.srt to /storage/sdcard0/Download/Subtitles/links..srt failed
```

**Comment by KillerJoeBR** [comment] 2019-04-07 13:20
@elgatito

I think the problem is that it tries to download the subtitle always using the same filename "links..srt". 

It works the first time but in the next time it can't overwrite the last file links..srt maybe because it is still in use somehow.

I think a possible simple solution if you can somehow make the filename to be numbered each try. Like first time links 1.srt
Then  links 2.srt, links 3.srt .... Etc... Etc

Would that be possible? Or Random generated? Perhaps this way it can always write the filename without failing

Thanks

**Comment by elgatito** [comment] 2019-04-07 13:22
```
2019-04-07 07:35:59.124 T:32584   ERROR: OnDownloadComplete - Saving of subtitle /storage/emulated/0/Download/Subtitles/Bumblebee.2018.1080p.BluRay.x264-SPARKS.srt to /storage/sdcard0/Download/Subtitles/links..srt failed
```

This is NOT done by Elementum. 
Elementum gives subtitles url to Kodi, everything else done by Kodi.

**Comment by KillerJoeBR** [comment] 2019-04-07 13:23
Maybe a different folder for each subtitle? Using the filename of the torrent or something like that. Just some ideas...

**Comment by KillerJoeBR** [comment] 2019-04-07 13:29
> ```
> 2019-04-07 07:35:59.124 T:32584   ERROR: OnDownloadComplete - Saving of subtitle /storage/emulated/0/Download/Subtitles/Bumblebee.2018.1080p.BluRay.x264-SPARKS.srt to /storage/sdcard0/Download/Subtitles/links..srt failed
> ```
> This is NOT done by Elementum.
> Elementum gives subtitles url to Kodi, everything else done by Kodi.

And the name "links" is not something it gets from elementum?

**Comment by elgatito** [comment] 2019-04-07 13:30
> And the name "links" is not something it gets from elementum?

No. It is taken from stream url.

**Comment by KillerJoeBR** [comment] 2019-04-07 13:36
Why while using opensubtitles addon it works fine?

For movie files where the opensubtitles get results normally I can download the subtitle without issues

**Comment by KillerJoeBR** [comment] 2019-04-07 13:41
Like I said there are 2 different problems that are related.

First elementum can't download the subtitle the second time. Using opensubtitles it works fine. 

Second problem is that elementum does not give the right info to the subtitles Add-ons and they can't find results. Mostly this issue is with TV episodes. Movies usually works

**Comment by KillerJoeBR** [comment] 2019-04-07 15:30
If I delete the links.srt file then elementum subtitle addon works. But then I need to delete it again for each use. 

Can I bind some key in my remote to delete the subtitle folder? Or a shortcut or something like that? This way it would fix the problem temporally till find a better solution.

**Comment by antonsoroko** [comment] 2019-04-07 15:36
I guess you can check kodi wiki, maybe it is possible to bind a key to run a script (.sh).

Also it would be interesting to see permissions of that file. E.g. ls -la , ls -Z , stat , fuser , lsof on that file in terminal.

**Comment by KillerJoeBR** [comment] 2019-04-07 15:47
Thanks, but I tried searching for a way to map a key to do this but I didn't get any viable results. Perhaps it's too complicated. No idea how to create a script to do that either.

**Comment by antonsoroko** [comment] 2019-04-07 16:04
First of all third is not really a solution.
Try to run commands i stated before in any terminal program (e.g. `ls -la /path/to/links.srt`) 

But if you want to implement this workaround, then:
Google for something like "kodi key to run script"
https://kodi.wiki/view/Keymap look for system.exec or runscript.
Simple shell script would be like
```
#!/bin/sh
rm /path/to/links.srt
```

**Comment by KillerJoeBR** [comment] 2019-04-07 18:03
@antonsoroko
Thanks I will try this later. I need to go out for the day (family stuff). At night I will try it. 

I appreciate your help. This script example you gave me I can just type it in the keymap or I need to create a script file and save it somewhere inside kodi? It looks too advanced for me.

Anyway thank you

**Comment by KillerJoeBR** [comment] 2019-04-07 18:28
I tried the ls terminal command

-rw-rw---- root

**Comment by antonsoroko** [comment] 2019-04-07 18:54
>I need to create a script file and save it somewhere

yes. i guess even download folder could work - e.g. `Downloads/del_sub.sh`. (if not, then probably your android has security features enables like selinux and it will be to tedious to explain options)
just google for something like "kodi key to run script" for examples

but anyway, this is not okay, i, for instance, don't have this issue . what device do you use? what is  android version? 

>-rw-rw---- root

you ran `ls -la /storage/sdcard0/Download/Subtitles/links..srt` , right?
it should produce a longer line
also please try `lsattr /storage/sdcard0/Download/Subtitles/links..srt`

**Comment by elgatito** [comment] 2019-04-08 10:21
@antonsoroko @KillerJoeBR I will try to test some ideas this week, but cannot guarantee it will help with subtitles' providers. Each provider is using own logic for getting played item information.

**Comment by KillerJoeBR** [comment] 2019-04-08 14:05
Ok I tried creating the script and executing it with a key but for some reason it is not working. For now I am using an addon to clear cache and custom paths. But it is not ideal cause it is not automate. I need to do it manually.

Thanks for looking this issue @elgatito. If you can at least make opensubtitle addon to work than it would be great. I and I guess a lot of people use it most of the time. 

Thanks

**Comment by elgatito** [comment] 2019-04-13 10:18
Please try with 0.1.25.

There are changes regarding OSDB:
1) OSDB is not working anonymously.
2) Links changed to don't have "links/play".
3) Auto-download option added.

**Comment by KillerJoeBR** [comment] 2019-04-13 10:47
@elgatito

Thanks. I will try it and report back. 
But in the downloads section the new version doesn't have an arm release. Seems to be missing something for a proper release? Maybe it's too soon? I will wait a little longer

**Comment by KillerJoeBR** [comment] 2019-04-13 10:48
Yup. It was too soon. There is a proper download now. I will try it

**Comment by KillerJoeBR** [comment] 2019-04-13 18:50
Ok my initial analisys.

The subtitle seems to be working much better now. It shows the name of the file you are watching and I get more results with another providers like opensubtitles and others.

So I guess this one is fixed. 

But I think I'm getting worse download speed now. It's not always. Seems more unstable. Like sometimes it's reconnecting lots of times. So it doesn't gain momentum and better speed.  But maybe it's the new torrents that I am trying. Need more testing

**Comment by KillerJoeBR** [comment] 2019-04-14 02:12
Ok further testings and the download speed seems to be fine. I guess it was my internet provider was slow at the time or maybe the torrent didn't have good seeds. 

Anyway everything looks fine now. 

Thanks @elgatito for your work

**Comment by elgatito** [comment] 2019-04-17 17:06
Closing this specific issue.

**Closed by elgatito** 2019-04-17 17:06 UTC
