### ISSUE TITLE
Daemon error 13 permission denied/ Elementum still starting up give it a few seconds errors

### ISSUE THREAD

**Issue by Stewiie3** [elgatito/plugin.video.elementum#832] opened 2021-10-08 00:43 UTC
I'm getting these two errors mentioned above, (daemon error 13 permission denied/ Elementum still starting up give it a few seconds) on the Android 10. I can't use the Elementum on my phone, however, on my laptop and on my tvbox the Elementum and all other add-ons works just fine. I can't find any solutions on Google.

**Comment by antonsoroko** [comment] 2021-10-08 10:25
See pinned issue on issues page. Or search for "Android 10" in issues here.

**Comment by elgatito** [comment] 2022-01-12 20:14
Duplicate of #669

**Closed by elgatito** 2022-01-12 20:14 UTC
