### ISSUE TITLE
Elementum subtitles not working

### ISSUE THREAD

**Issue by KillerJoeBR** [elgatito/plugin.video.elementum#410] opened 2019-04-07 10:56 UTC
First of all, this wouldn't be a big problem if searching subtitle with other providers did work.

This is a problem mostly with TV episodes. Only elementum provider find results. Even opensubtitles can't find any results and other ones that work fine while watching a movie file. 

Seems like elementum doesn't give enough information for these other providers and they can't find any results. It at least should work with opensubtitles since it's the same provider inside elementum. 

Anyway elementum finds the subtitle but it gives error while trying to download it. Seems like it only works the first time then it fails every other time. If I can find the subtitle using the opensubtitles addon I can download the subtitle just fine. It only fails while using elementum. The problem is most recent TV episodes I can't find any results only in elementum. 

Write permission issue?  I think because it always use the same filename "links"? In quasar it would provide the filename from the episode you were watching I think. 

So I would like to fix the issue that fails the subsequent downloads and it would also be great if you could change the info to other Add-ons like opensubtitles (and others) so it could also find results. 

https://paste.ubuntu.com/p/DsjmY4yH3p

**Comment by KillerJoeBR** [comment] 2019-04-07 11:02
BTW, I am using an older elementum version cause the newer ones seems to have a bug where it tries to search for a movie or TV episode but burst doesn't work. I see that it opens burst but it closes immediately without any results. I need to close kodi and open again for the burst search to work again. I will try to open an new issue for this one.

Thanks,

**Comment by elgatito** [comment] 2019-04-07 12:18
Duplicate of #282  and #196 .

**Closed by elgatito** 2019-04-07 12:18 UTC

**Comment by antonsoroko** [comment] 2019-04-07 12:56
@KillerJoeBR 
i think your issue is more related to https://github.com/elgatito/plugin.video.elementum/issues/196

also i guess you use kodi 18. there is not such issue with kodi 17. in some plugins (e.g. addic7ed - check it out, btw) you can set option like "use filename" - which worked for kodi 18 for me, if i recall correctly. (for kodi 17 i still have to use this option by some reason)
