### ISSUE TITLE
Xbox Support

### ISSUE THREAD

**Issue by Dodo21odoD** [elgatito/plugin.video.elementum#1047] opened 2024-05-28 22:27 UTC
Can you add support for watching movies from elementium on Xbox Series X/S?

**Comment by antonsoroko** [comment] 2024-06-12 13:21
please use search https://github.com/elgatito/plugin.video.elementum/issues?q=is%3Aissue+Xbox
it was discussed many times already.
the only way with xbox is to use client-server approach: you run kodi+elementum as client on xbox and then elementum as server on PC. see the end of https://github.com/elgatito/plugin.video.elementum/issues/2

**Comment by elgatito** [comment] 2024-07-18 15:34
Duplicate of #844

**Closed by elgatito** 2024-07-18 15:34 UTC
