### ISSUE TITLE
No module named platform_detect.python.platform

### ISSUE THREAD

**Issue by arielgrin** [elgatito/plugin.video.elementum#926] opened 2023-07-03 12:18 UTC
## Expected Behavior

Elementum should launch
## Current Behavior

Elementum doesn't launch on Kodi 18 running on Chromecast with Google TV
## Possible Solution

Version 0.1.86 run correctly, now it isn't running probably due to the switch to detect_platform project
## Steps to Reproduce (for bugs)

1. Install new plugin version 0.1.88 from elementum.surge.sh
2. Try to run Elementum
3. Elementum throws error
4. Error log shows following error:
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named platform_detect.python.platform
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/navigation.py", line 4, in <module>
                                                from elementum import navigation
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 20, in <module>
                                                from elementum.osarch import PLATFORM
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/osarch.py", line 8, in <module>
                                                from platform_detect.python.platform import detect_platform
                                            ImportError: No module named platform_detect.python.platform
                                            -->End of Python script error report<--
2023-07-03 08:51:37.928 T:917   DEBUG: onExecutionDone(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/navigation.py)

## Your Environment

* Version used: 0.1.88

* Environment name and version: Kodi 18.9

* Operating System and version: Android 12 on Chromecast with Google TV

* Link to Kodi debug log: https://paste.kodi.tv/aloxevulik.kodi

**Comment by elgatito** [comment] 2023-07-03 12:25
@arielgrin Try installing v0.1.89. If error is still there - restart Kodi and post full log file, to see what is there.

**Comment by arielgrin** [comment] 2023-07-03 12:30
I installed 0.1.89 but unfortunately the same error persists

2023-07-03 09:29:36.314 T:1400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named platform_detect.python.platform
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/service.py", line 4, in <module>
                                                from elementum import service, config
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/service.py", line 4, in <module>
                                                from elementum.rpc import server_thread
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/rpc.py", line 16, in <module>
                                                from elementum.osarch import PLATFORM
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/osarch.py", line 8, in <module>
                                                from platform_detect.python.platform import detect_platform
                                            ImportError: No module named platform_detect.python.platform
                                            -->End of Python script error report<--

**Comment by elgatito** [comment] 2023-07-03 12:39
Again you are not doing what I am asking.
Post full log file.
Which zip file you downloaded?

**Comment by arielgrin** [comment] 2023-07-03 12:49
I downloaded the Android ARM file and also tried the Universal All-in-one file.

Sorry if I didn't understand correctly, but this is the log from the moment I installed the plugin

https://paste.kodi.tv/tirukupohu.kodi

**Comment by elgatito** [comment] 2023-07-03 13:00
@arielgrin Which URL you used to download zip file? Can you give exact url, so that I can inspect what is inside.

**Comment by arielgrin** [comment] 2023-07-03 13:07
I opened https://elementum.surge.sh and I clicked on Android arm link and that downloaded the file.

If I right click the link and select copy link, the copied link is https://github.com/elgatito/plugin.video.elementum/releases/download/v0.1.89/plugin.video.elementum-0.1.89.android_arm.zip

There is something strange with this. If I click the link from elementum.surge.sh, the file that is downloaded can be installed but the plugin doesn't run as explained before. If I go to github and dowload the same file from the releases section and try to install it, Kodi shows the error that the plugin can't be installed due to an invalid structure. Because of this I can't go back to the previous version that worked for me, v0.1.87

Is there a way to download a previous version so I can use the plugin in the meantime?

**Comment by elgatito** [comment] 2023-07-03 13:20
Sorry, I don't understand.
elementum.surge.sh is pointing to latest release.
You can download any version manually from https://github.com/elgatito/plugin.video.elementum/releases .

There was a bug in early 0.1.88 with wrong file structure, but it was fixed. Maybe you try to install same broken zip file. Link you have posted is correct. I have tried to download and install it.
Make sure you install from correct zip file.

**Comment by arielgrin** [comment] 2023-07-03 13:23
I installed from elementum.surge.sh and it correctly installed the latest version 0.1.89 but it shows the error: "No module named platform_detect.python.platform"

https://paste.kodi.tv/tirukupohu.kodi

**Comment by arielgrin** [comment] 2023-07-03 13:48
I installed Kodi 20.2 and tried to install elementum plugin from elementum.surge.sh and the plugin installs and run, but L2tHttp now gives error [Errno 13] Permission denied: '/data/data/org.xbmc.kodi/files/service.lt2http/bin/android-arm/lt2http'

Is there any way to download plugin version 0.1.86 or 0.1.87 that will work? The download from releases shows error "can't install due to invalid structure"

L2tHttp error: https://paste.kodi.tv/sonibopetu.kodi

**Comment by elgatito** [comment] 2023-07-03 13:49
@arielgrin No. You installed v0.1.88 again.

```
2023-07-03 09:46:01.924 T:1729  NOTICE: ADDON: plugin.video.elementum v0.1.88 installed
```

**Comment by arielgrin** [comment] 2023-07-03 13:51
I don't understand why it says 0.1.88 because I used the elementum.surge.sh link which is supposed to point to the latest release

**Comment by elgatito** [comment] 2023-07-03 13:56
@arielgrin Make sure you install *actual* zip file. And not the one you keep installing again and again.

**Comment by arielgrin** [comment] 2023-07-03 13:58
I don't know what else to do. I only have the file that I downloaded from elementum.surge.sh

**Comment by arielgrin** [comment] 2023-07-03 14:00
I re-downloaded the All-in-one file and now I get the error that the plugin file has an invalid structure and can't be installed.

**Comment by arielgrin** [comment] 2023-07-03 14:22
I uninstalled kodi and reinstalled version 20.2 and re-downloaded the All-in-one version from elementum.surge.sh and I was able to install the elementum plugin, but now I get the errno 13 when I try to install the L2THttp service

I will open a new issue for that.

Could you please tell me how to download the previous version 0.1.86 or 0.1.87 ?
If I try to download from the releases section of github, Kodi can't install it because the file structure is invalid

**Comment by arielgrin** [comment] 2023-07-03 14:30
I can confirm that v0.1.89 does not work on Kodi 18.9 with the following error

2023-07-03 11:29:02.697 T:7861   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named platform_detect.python.platform
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/service.py", line 4, in <module>
                                                from elementum import service, config
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/service.py", line 4, in <module>
                                                from elementum.rpc import server_thread
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/rpc.py", line 16, in <module>
                                                from elementum.osarch import PLATFORM
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/osarch.py", line 8, in <module>
                                                from platform_detect.python.platform import detect_platform
                                            ImportError: No module named platform_detect.python.platform
                                            -->End of Python script error report<--

Please let me know how to install previous version 0.1.86 or 0.1.87

**Comment by elgatito** [comment] 2023-07-03 14:36
> Could you please tell me how to download the previous version 0.1.86 or 0.1.87 ?

I was already writing this. Download zip file and install it manually in Kodi.

**Comment by arielgrin** [comment] 2023-07-03 14:38
Can you provide the correct link to download? If I use following links, I get the error "invalid file structure" and can't install it

https://github.com/elgatito/plugin.video.elementum/releases/download/v0.1.87/plugin.video.elementum-0.1.87.android_arm.zip

https://github.com/elgatito/plugin.video.elementum/releases/download/v0.1.86/plugin.video.elementum-0.1.86.android_arm.zip

**Comment by arielgrin** [comment] 2023-07-03 15:06
I was able to install v0.1.87 after uninstalling and re-installing Kodi 18.9

There is some issue related to detect_platform with Kodi 18.9 that prevents v0.1.89 from working

**Comment by pavelmxx** [comment] 2023-07-03 23:56
Autoupdated from previos version. Same problem.
```
2023-07-04 02:42:47.805 T:10356 NOTICE: -----------------------------------------------------------------------
2023-07-04 02:42:47.805 T:10356 NOTICE: Starting Kodi (18.9 (18.9.0) Git:20201023-0655c2c718). Platform: Windows NT x86 64-bit
2023-07-04 02:42:47.805 T:10356 NOTICE: Using Release Kodi x64 build
2023-07-04 02:42:47.805 T:10356 NOTICE: Kodi compiled 2020-10-23 by MSVC 191627035 for Windows NT x86 64-bit version 10.0 (0x0A000007)
2023-07-04 02:42:47.805 T:10356 NOTICE: Running on Windows 7 SP1, kernel: Windows NT x86 64-bit version 6.1.7601
2023-07-04 02:42:47.805 T:10356 NOTICE: FFmpeg version/source: 4.0.4-Kodi
...
2023-07-04 02:47:40.689 T:12000 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
 Error Type: <type 'exceptions.ImportError'>
 Error Contents: No module named platform_detect.python.platform
 Traceback (most recent call last):
 File "C:\Kodi_portable\kodi\portable_data\addons\plugin.video.elementum\service.py", line 4, in <module>
 from elementum import service, config
 File "C:\Kodi_portable\kodi\portable_data\addons\plugin.video.elementum\resources\site-packages\elementum\service.py", line 4, in <module>
 from elementum.rpc import server_thread
 File "C:\Kodi_portable\kodi\portable_data\addons\plugin.video.elementum\resources\site-packages\elementum\rpc.py", line 16, in <module>
 from elementum.osarch import PLATFORM
 File "C:\Kodi_portable\kodi\portable_data\addons\plugin.video.elementum\resources\site-packages\elementum\osarch.py", line 8, in <module>
 from platform_detect.python.platform import detect_platform
 ImportError: No module named platform_detect.python.platform
 -->End of Python script error report<--
```

**Comment by pavelmxx** [comment] 2023-07-04 00:21
Same on Windows 10.
```
2023-07-04 02:38:45.699 T:2888 NOTICE: -----------------------------------------------------------------------
2023-07-04 02:38:45.699 T:2888 NOTICE: Starting Kodi (18.9 (18.9.0) Git:20201023-0655c2c718). Platform: Windows NT x86 64-bit
2023-07-04 02:38:45.699 T:2888 NOTICE: Using Release Kodi x64 build
2023-07-04 02:38:45.699 T:2888 NOTICE: Kodi compiled 2020-10-23 by MSVC 191627035 for Windows NT x86 64-bit version 10.0 (0x0A000007)
2023-07-04 02:38:45.700 T:2888 NOTICE: Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.19045
2023-07-04 02:38:45.700 T:2888 NOTICE: FFmpeg version/source: 4.0.4-Kodi
...
2023-07-04 02:39:00.498 T:8800 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
 Error Type: <type 'exceptions.ImportError'>
 Error Contents: No module named platform_detect.python.platform
 Traceback (most recent call last):
 File "C:\Kodi_portable\kodi\portable_data\addons\plugin.video.elementum\service.py", line 4, in <module>
 from elementum import service, config
 File "C:\Kodi_portable\kodi\portable_data\addons\plugin.video.elementum\resources\site-packages\elementum\service.py", line 4, in <module>
 from elementum.rpc import server_thread
 File "C:\Kodi_portable\kodi\portable_data\addons\plugin.video.elementum\resources\site-packages\elementum\rpc.py", line 16, in <module>
 from elementum.osarch import PLATFORM
 File "C:\Kodi_portable\kodi\portable_data\addons\plugin.video.elementum\resources\site-packages\elementum\osarch.py", line 8, in <module>
 from platform_detect.python.platform import detect_platform
 ImportError: No module named platform_detect.python.platform
 -->End of Python script error report<--
```

**Comment by elgatito** [comment] 2023-07-04 05:29
@pavelmxx What version is installed there? Try to download the latest and install from zip file.

**Comment by innovaciones** [comment] 2023-07-04 17:08
I confirm that version 0.1.89 and 0.1.88 are not working in macOS (Kodi 18.9), I get the same error from the log:

`ImportError: No module named platform_detect.python.platform`

Version 0.1.87 works fine

**Comment by elgatito** [comment] 2023-07-04 17:26
@innovaciones Try to install latest version, then restart Kodi and share full log.

**Comment by innovaciones** [comment] 2023-07-04 18:04
Sure, here is the full log after installing [plugin.video.elementum-0.1.89.darwin_x64.zip](https://github.com/elgatito/plugin.video.elementum/releases/download/v0.1.89/plugin.video.elementum-0.1.89.darwin_x64.zip) and restarting Kodi

https://paste.kodi.tv/pibukufoku.kodi

**Comment by pavelmxx** [comment] 2023-07-04 21:11
I deleted Elementum completely, include settings.
Downloaded from link https://github.com/elgatito/plugin.video.elementum/releases/download/v0.1.89/plugin.video.elementum-0.1.89.windows_x64.zip/
Install from recently downloaded zip file.
Restarted Kodi with killing Elementum.exe process in task manager.
Same result. " ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--"
I didn’t reinstall burst, context help, repository. Only Elementum.

**Comment by adamantivm** [comment] 2023-07-04 22:43
I have the same issue on Kodi 18.7 running on the latest Retropie (raspberry pi 4).
I was able to get things working again by downgrading to 0.1.87, even though downgrading was quite the struggle: I downloaded the zip file for my system but when I install it, as soon as it installs, it gets auto-updated.
I ended up manually replacing the files inside the .kodi/addons directory and cheating the version number to something higher so that it doesn't get replaced.

I hope we can get a fixed to get back on track again.
Anyway thanks a lot for this addon @elgatito

**Comment by ramiro** [comment] 2023-07-05 00:49
Seeing the same issue.

Platform: Android TV 7 (android_arm) (smart TV)
Kodi: v18.9
Installation method: Plugin Auto upgrade from inside Kodi.

If I download the zip file linked in Downloads section of Elementum website form my TV platform (https://github.com/elgatito/plugin.video.elementum/releases/download/v0.1.89/plugin.video.elementum-0.1.89.android_arm.zip) and
the master archive of `platform_detect` from https://github.com/ElementumOrg/platform_detect/archive/master.zip, unzip  and compare them I see two possible reasons for the failure:

1. All `resources/site-packages/platform_detect/libraries/*/` paths in the Elementum zip are missing their `test.so`files. Windows DLL are there. So it seems the new code in `release.sh` somehow got an incomplete `platform_detect`  `master.zip` or something else removed these .so files in the process
2. The `resources/site-packages/platform_detect/` directory has no `__init__.py` file. Not sure it's actually needed tough.

For now, got Elementum working again by:
* Disabling auto-updates for the plugin
* Downloading https://github.com/elgatito/plugin.video.elementum/releases/download/v0.1.87/plugin.video.elementum-0.1.87.android_arm.zip and installing it via Kodi's Add-ons -> Install from .zip file option

**Comment by ramiro** [comment] 2023-07-05 01:45
Got v0.1.89 working again by doing the following:

* Manually modified `plugin.video.elementum-0.1.89.android_arm.zip` to

  * Add an empty `__init__.py` file in `resources/site-packages/platform_detect/`
  * Also add an empty `__init__.py` file in `resources/site-packages/platform_detect/python/` (otherwise the import error message is about `python.platform`
  * Add back the missing `test.so` files under `libraries/` (although their absence most probably would have caused a different error that would have appeared afterwards)

* Installed the modified .zip file via Kodi's _Add-ons_ -> _Install from .zip file_ option.

**Comment by ramiro** [comment] 2023-07-05 03:07
Ok. So I went to another Android device that has Kodi 19.5. Elementum got auto- upgraded to 0.1.89 and it's s working perfectly.

I think I understand now what's happening: The common factor between all the reporters here is Kodi 18.

Kodi 18 bundles Python 2. And Kodi >= 19 bundle Python 3. I had forgotten about that.

I'm guessing Python 2 is more limited/restrictive compared with Python 3 when it comes to modules/packages missing __init__.py files. 

All tests I performed in the REPL importing platform and trying to reproduce the error  were done using python 3. And this explains why I was unable to reproduce it.

Will redo them tomorrow with Python 2 to confirm.

**Comment by pitsi** [comment] 2023-07-05 04:04
If it helps, may I add that I have the same issue on my kodi 18.9 installation (libreelec 9.2.6 x64)? Sadly, this is the only working kodi installation I have right now and the only one that has elementum installed, so I do not have a way to see what happens on python3 versions :(

**Comment by elgatito** [comment] 2023-07-05 09:17
Please, try to install v0.1.90.

**Comment by pitsi** [comment] 2023-07-05 09:49
I just did the upgrade to 0.1.90 (from the linux x64 zip, because that is the right one for my platform) and it still fails to load. 
```
2023-07-05 12:37:54.906 T:140654906513152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named python.platform
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.elementum/navigation.py", line 4, in <module>
                                                from elementum import navigation
                                              File "/storage/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 20, in <module>
                                                from elementum.osarch import PLATFORM
                                              File "/storage/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/osarch.py", line 8, in <module>
                                                from platform_detect.python.platform import detect_platform
                                            ImportError: No module named python.platform
                                            -->End of Python script error report<--
2023-07-05 12:37:54.988 T:140655112206080   ERROR: GetDirectory - Error getting plugin://plugin.video.elementum/
2023-07-05 12:37:54.991 T:140656395257984   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.elementum/) failed
```
But right before that, when it was still on 0.1.89, I did check for the missing .so files from all the unix related folders and they were missing indeed. Now they are all there.
I wanted to create the two __init__.py files mentioned above, just as mentioned above, but the file is already there on the first folder and the python folder does not exist in there. Proof
```
:~/.kodi/addons/plugin.video.elementum/resources/site-packages/platform_detect # ls -R
.:
__init__.py   __init__.pyo  libraries     platform.py

./libraries:
android_arm    android_x86    linux_armv6    linux_x86
android_arm64  darwin_x64     linux_armv7    windows_x64
android_x64    linux_arm64    linux_x64      windows_x86

./libraries/android_arm:
test.h   test.so

./libraries/android_arm64:
test.h   test.so

./libraries/android_x64:
test.h   test.so

./libraries/android_x86:
test.h   test.so

./libraries/darwin_x64:
test.h   test.so

./libraries/linux_arm64:
test.h   test.so

./libraries/linux_armv6:
test.h   test.so

./libraries/linux_armv7:
test.h   test.so

./libraries/linux_x64:
test.h   test.so

./libraries/linux_x86:
test.h   test.so

./libraries/windows_x64:
test.dll  test.h

./libraries/windows_x86:
test.dll  test.h

```

**Comment by weekendsource** [comment] 2023-07-05 10:14
Well, at least for windows version of elementum: in 1.90, comparing to 1.89, file platform.py was moved from resources/site-packages/platform_detect/python to resources/site-packages/platform_detect and folder resources/site-packages/platform_detect/python does not exist anymore. 

So, either make folder python in resources/site-packages/platform_detect and copy/move platform.py there, or change line 8 in resources/site-packages/elementum/osarch.py from:
`from platform_detect.python.platform import detect_platform`
to
`from platform_detect.platform import detect_platform`

**Comment by pitsi** [comment] 2023-07-05 10:16
@weekendsource 
Do these instructions apply to my issue as well? If so, I will try them in like 10 minutes. Thanks in advance.

**Comment by elgatito** [comment] 2023-07-05 10:19
@weekendsource yes, forgot to update that file. Preparing new version.

**Comment by weekendsource** [comment] 2023-07-05 10:21
@pitsi 
↑↑↑ Here's the answer from the boss :)

**Comment by pitsi** [comment] 2023-07-05 10:33
I patched the line you mentioned and it is now stuck on "elementum is still launching, please wait" :P 
No errors in the log though, which is finally a good sign. I rebooted it twice and disabled and re-enabled elementum too.

**Comment by elgatito** [comment] 2023-07-05 11:07
Version 0.1.91 is available. Please, try it.

**Comment by ramiro** [comment] 2023-07-05 11:21
0.1.191 is working perfectly. Thanks Denis!

**Comment by pitsi** [comment] 2023-07-05 11:30
Working great here as well! Well done :)

**Comment by adamantivm** [comment] 2023-07-05 11:38
That was quick turnaround. Any idea how long until it's available in the Element repository, so I can try it from there, back to the normal update flow?

**Comment by elgatito** [comment] 2023-07-05 11:40
It is already in the "repository". But since Elementum is acting as a repository - if Elementum is down - repo is also down. So just get a zip and install it.

**Comment by adamantivm** [comment] 2023-07-05 11:45
ok, not sure I understand how that works but anyway, installed manually and I can also confirm 0.1.91 working fine for Kodi 18.7 on Retropie, thanks!  :+1:

**Comment by dineshalphaque** [comment] 2023-07-05 12:32
Got into the thread late, but I was having the same platform_detect ossue with Kodi 20.1 on arm7 as well. And the 0.1.91 update fixed it back alright, so just to leave this here in case Kodi 20.x users swing by.

**Comment by innovaciones** [comment] 2023-07-05 19:59
Thanks for the fix, the error is gone and torrents are working fine using the Web UI, except one thing, my current skin Artic Horizon (Kodi 18.9) is not showing anything when I open Movies or TV Shows, I test other skins like Estuary and Aeon Nox and they work fine so I guess the issue is with my skin and the window ID, the thing is previous version 0.1.87 worked fine with my skin, anyway just want to report this not expecting any fix and thank you for still supporting old Kodi versions, I really appreciate all the work you do with this amazing addon.

**Comment by ha11oga11o** [comment] 2023-07-06 06:31
I installed [this link](https://github.com/elgatito/plugin.video.elementum/releases/download/v0.1.91/plugin.video.elementum-0.1.91.zip) on LibreElec 9.2.8 (RPI3b+) but it seems it cant install Burst. It tries but point me to install it manually. When i select Elementum repository it says cannot connect to it. Am i missing something here? I uninstalled Elementum, Burst and old repo. Then install it from zip. 

If someone knows what im doing wrong will you please point me to right direction?

Thnx.

**Comment by pitsi** [comment] 2023-07-06 06:38
Did you reboot the system or restart kodi before trying to install burst?
Elementum has to be loaded and working for its repo to work, and in turn its repo has to work for you to install burst.

**Comment by ha11oga11o** [comment] 2023-07-06 06:55
Ohh, no. I remove everything, install, but i did reboot when problems started. It seems i need to remove everything now and reboot. AND then try to install it. [Here](https://elementumorg.github.io/getting-started/updating/) at bottom says no need to remove, but i did remove it. Ill try to delete everything, including repo, reboot, and do everything from scratch. Thanks for tip.

**Comment by matke-84** [comment] 2023-07-06 17:03
I can't install burst because it can't connect to the repository. I tried everything and there is no way to connect to the repository. There is definitely something messed up since version 0.1.87 which works normally.

**Comment by ha11oga11o** [comment] 2023-07-06 18:40
I did everything from scratch and still dont want to install burst. Elementum works but cant fetch data because theres no burst. But, from download page i took burst zip and install it manually from that and now all works fine. Still cant connect to elementum tho. 

Thank you guys, kids are happy now. Cheers!

**Comment by matke-84** [comment] 2023-07-06 19:23
It's not a problem to install manually, but that's not the point. It should work as before. I hope @elgatito will sort this out.

**Comment by ramiro** [comment] 2023-07-06 19:53
I'd suggest to open another issue and stop posting about that unrelated issue here so it can be closed.

**Comment by elgatito** [comment] 2023-07-07 14:46
@innovaciones Please, open a separate issue with all the details, and Kodi log (after trying to enter some folder in elementum addon).

2 days and no logs provided with repository failure.

Closing this one. There is already an issue about repository.

**Closed by elgatito** 2023-07-07 14:46 UTC
