### ISSUE TITLE
[Bug] Elementum is downloading with normal speed only on initial buffer

### ISSUE THREAD

**Issue by unster** [elgatito/plugin.video.elementum#105] opened 2018-02-16 18:47 UTC
Hi,

since version 42 I can't normally watch videos with Elementum. Any video content is being downloaded only while initial buffer is being fulled. 

**Repro steps:**
1. Select any video material:
![Torrents found](https://i.imgur.com/V4Y30Gq.jpg)
2. Initial buffering starts with max speed after 2-3 seconds (~7 Mb/s). Everything is fine so far,
3. First ~10-15% of video is loaded, video playback starts and I pause video so more content could buffer. Then download speed falls drastically, like on video:
https://www.youtube.com/watch?v=h7JYS-7D6aw
Notice the freeze and then drop to 0 after 10 seconds.

When I check torrent download folder I have a lot of folders there with shows that I tried to load, sometimes there are full files download, although I have no active torrents for them. Can it be related? 

My BitTorrent section settings:
![b1](https://i.imgur.com/DaUDST0.jpg)
![b2](https://i.imgur.com/thwCRcI.jpg)

**Environment:**
Version used: .43
Environment name and version: linux_arm64
Operating System and version: LibreELEC (Krypton) 8.2.2
Device: Odroid-C2
Additional info: I have last Quasar & Quasar-Burst still installed as I am using them till I solve this issue (working for already added shows - months ago)
Link to Kodi debug log: to be uploaded if requested

**Comment by unster** [comment] 2018-02-16 19:15
When I was recording log a slightly different behavior was noted. It finished initial buffering, then I paused video and starter buffering - almost top speed was recorder, but every ~30 seconds buffer froze, went down to 0 and then up to top speed. In summary it was loaded very slowly.

Log: http://ix.io/KZx backup: https://paste.ee/p/USuHO

**Comment by veniciusgp** [comment] 2018-02-17 16:59
I face exactly this same problem. Using the quasar in the same movie / tv show I get the maximum speed of my connection, but with the elementum the speed becomes quite unstable.

**Comment by elgatito** [comment] 2018-02-17 17:17
@unster , please, set buffer to, at maximum, 50mb, and give a log file where I could see how buffering ends, playback started and few minutes more (can be paused).

**Comment by unster** [comment] 2018-02-17 21:41
updated log: http://ix.io/LBP

**Comment by unster** [comment] 2018-02-21 17:35
Hi @elgatito ! Well, at the moment due to this problem Elementum is not usable for me. I tried to watch a movie yesterday and after hour of buffering I barely passed 16% of buffering. It goes from 7mb/s to 0 or 20 kb/s randomly, every few seconds. Can you please have a look on updated log I provided?

**Comment by Jezze83** [comment] 2018-03-10 07:45
Same problem here, addon is unusable.

**Comment by undead-osiris** [comment] 2018-03-11 23:10
maybe it's connected to in memory file store type. After i've changed it to file storage speed is back to normal.

[screenshot](https://www.dropbox.com/s/mu83k7ypbxw2t66/Screenshot%202018-03-12%2002.01.51.png?dl=0)

**Comment by hmvs** [comment] 2018-03-20 22:05
Actually for me it is vice versa. I can't use file storage at all. Seems while it dumps the downloaded part to the disk -disk is overloaded and it can't read from it (my guess). Movie starts lagging with message "Source is too slow". Even though it downloaded more than a half of movie, it lags on first two minutes. 
Tried on SSD - same story. 
Memory playback works fine, But I would like to use file, to be able to precache it.

**Comment by unster** [comment] 2018-04-21 20:05
Hi @elgatito I see you continue Elementum development, thanks! Any chance that you will look closer this issue?

**Comment by elgatito** [comment] 2018-04-27 04:55
@unster This addon does not manage "file" storage, it is all done from the torrent library (https://github.com/anacrolix/torrent). We have only memory storage, that is managed from the addon's side.
For file storage it downloads all the file, so tried to do that as fast as possible (if rate limit was not set).

**Comment by elgatito** [comment] 2018-04-27 05:00
@hmvs if you think there is a bug - file an issue. 
Your Kodi has increased buffer in advancedsettings.xml:
```
<cachemembuffersize>252420000</cachemembuffersize>
```

So it wants to get 25Mb of file to be available. Try to increase memory size a little, and increase buffer (BitTorrent settings tab) to 25Mb.

**Comment by elgatito** [comment] 2018-05-14 04:48
@unster , any change?

**Comment by joelvdvoort** [comment] 2018-05-14 22:07
I can confirm this problem on file storage as well. Download seems to start up and stall very often. Might this have something to do with filling up the buffer and stalling the download, only to start it up right after it needs to fill up the buffer again? If that's how the ram storage system works, it seems to applied to file storage as well. I'll test some more tomorrow and see if it works well enough on ram storage. Torrent download speeds can be annoyingly slow to ramp up so I'm a bit skeptical of this system but I have to try first.

If there's any specific diagnostics I have to collect please let me know.

**Comment by IkenHuub** [comment] 2018-05-14 22:31
Same problem here. It seems something is limiting the download at some point. This is not working for me. Too bad because Quasar worked at top speed all the time. I tried everything. :(

**Comment by elgatito** [comment] 2018-06-13 08:35
@unster  is this bug still reproduced in 0.0.47 ?  It happen only with file storage?

**Comment by elgatito** [comment] 2018-06-14 07:34
With 0.0.48, please, try this issue, if happen - open `/debug/bundle` and share the downloaded log file.

http://192.168.0.1:65220/debug/bundle (replace 192.168.0.1 with your Kodi IP)

**Comment by herrwusel** [comment] 2018-06-17 12:01
I think I'm experiencing the same behaviour. Here is what I did:
Chose a torrent and let the download run in background (wasn't watching). In the webinterface I could see that the speed was very unstable whereas I was at full speed in the beginning.
[bundle_2018_6_16_8_5.log](https://github.com/elgatito/plugin.video.elementum/files/2108919/bundle_2018_6_16_8_5.log)

**Comment by elgatito** [comment] 2018-06-19 05:31
@unster @IkenHuub @Jezze83 can somebody start a download with file storage, if having low speeds -open /debug/bundle and share the downloaded log file.

http://192.168.0.1:65220/debug/bundle (replace 192.168.0.1 with your Kodi IP)

**Comment by elgatito** [comment] 2018-07-13 10:56
Closing this issue.
Execution of a fix can be tracked here - https://github.com/anacrolix/torrent/issues/265

**Closed by elgatito** 2018-07-13 10:56 UTC
Labels: bug
