### ISSUE TITLE
No module named platform_detect.python.platform on Raspberry pi 4

### ISSUE THREAD

**Issue by dm-shlandii** [elgatito/plugin.video.elementum#938] opened 2023-07-20 11:29 UTC
Was using Elementum for few years and with some recent update it just crash (kodi is still running tho). (Had autoupdate turned on). Not sure when it start to fail because have not used it for last few months. Will try to revert into 0.1.87

## Possible Solution
Noticed some recent commits related to platform detect. But not very proficient in python.

## Steps to Reproduce (for bugs)
1. Start Kodi
2. Elementum addin report fail immediately

* Version used:
Elementum 0.1.92
* Environment name and version:
Linux raspberrypi4 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
Kodi 18.7
* Operating System and version:
Raspberry pi 4
Raspbian(debian based)
Linux raspberrypi4 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

* Link to Kodi debug log:
2023-07-20 08:54:20.992 T:2972720256 WARNING: Repository add-on repository.elementum uses plain HTTP for add-on downloads in path http://127.0.0.1:65220/repository/elgatito/ - this is insecure and will make your Kodi installatio$
2023-07-20 08:54:21.156 T:2972720256 WARNING: Previous line repeats 2 times.
2023-07-20 08:54:21.156 T:2972720256 WARNING: CGUIMediaWindow::OnMessage - updating in progress
2023-07-20 08:54:21.204 T:2565361856 WARNING: Repository add-on repository.elementum uses plain HTTP for add-on downloads in path http://127.0.0.1:65220/repository/elgatito/ - this is insecure and will make your Kodi installatio$
2023-07-20 08:54:21.241 T:2768113856 WARNING: Previous line repeats 2 times.
2023-07-20 08:54:21.241 T:2768113856   ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for http://127.0.0.1:65220/repository/elgatito/plugin.video.elementum/icon.png
2023-07-20 08:54:21.672 T:2718183616   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named platform_detect.python.platform
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.elementum/service.py", line 4, in <module>
                                                from elementum import service, config
                                              File "/home/kodi/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/service.py", line 4, in <module>
                                                from elementum.rpc import server_thread
                                              File "/home/kodi/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/rpc.py", line 16, in <module>
                                                from elementum.osarch import PLATFORM
                                              File "/home/kodi/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/osarch.py", line 8, in <module>
                                                from platform_detect.python.platform import detect_platform
                                            ImportError: No module named platform_detect.python.platform
                                            -->End of Python script error report<--

**Comment by elgatito** [comment] 2023-07-20 11:38
Duplicate of https://github.com/elgatito/plugin.video.elementum/issues/934 . Re-download zip file of version 0.1.92 and re-install it on top.

**Closed by elgatito** 2023-07-20 11:38 UTC
