### ISSUE TITLE
[Bug]Daemon error: Attribute error for ios 11.2.1 and kodi krypton

### ISSUE THREAD

**Issue by vrknetha** [elgatito/plugin.video.elementum#72] opened 2018-01-24 08:35 UTC
## Steps to Reproduce (for bugs)

1. Switch on the settings in services
2. Install from zip file
3. Restart Kodi
4. Observe the error

## Context
I have installed the addon and restarted the Kodi and I could see this error
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/1659112/kodi.log)

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment] 2018-01-24 08:37
IOS not yet supported because of IOS limitations.

Duplicate of #4

**Closed by elgatito** 2018-01-24 08:37 UTC
