### ISSUE TITLE
Can't add .torrent manually anymore.

### ISSUE THREAD

**Issue by lanzorg** [elgatito/plugin.video.elementum#156] opened 2018-05-11 10:17 UTC
The file/url selection box disappeared completely!  
![img_20180511_120608](https://user-images.githubusercontent.com/994926/39919830-2b848d5a-5515-11e8-9e71-9afc6216849b.jpg)

**Comment by lanzorg** [comment] 2018-05-11 11:33
You are right, I am using an alpha release.  
I will try with a different skin. ;)

**Comment by herrwusel** [comment] 2018-05-11 11:37
You might need to go back to a stable release to get it working again :/

**Comment by lanzorg** [comment] 2018-05-11 11:49
Do you mean it can't be fixed?  
I use CoreELEC on S905 Amlogic device and there is no build based on Krypton. :(

**Comment by elgatito** [comment] 2018-05-11 11:57
@lanzorg CoreElec started few weeks ago, that is why they have only Leia builds. You can wait until they make newer versions, and maybe include latest fixes from Kodi. Or use LibreElec builds, based on Krypton.

If the bug is not a bug, but a change in Kodi API, then it's another thing. At the moment I can't help with alpha Kodi testing.

**Comment by herrwusel** [comment] 2018-05-11 12:02
@lanzorg: Check [here](https://forum.libreelec.tv/thread/9319-8-2-3-1-libreelec-8-2-for-s905-s905x/) for a Krypton based libreelec.

**Comment by lanzorg** [comment] 2018-05-11 12:06
@herrwusel: I don't have smooth/bug-free playback with it. :(

**Comment by elgatito** [comment] 2018-05-14 04:25
Is it a bug in the skin? Or a change in the API? Other plugins that use file selection work fine?

**Comment by lanzorg** [comment] 2018-05-14 12:50
I have the same issue with other skins, so it's probably a change in the API.

**Comment by elgatito** [comment] 2018-06-20 06:02
Any news with the latest Kodi/skin versions?

**Comment by elgatito** [comment] 2018-07-13 10:52
@lanzorg do you have any news? Still got this issue?

**Comment by bugatsinho** [comment] 2018-07-18 14:53
i can add .torrent file using the default kodi17 skin my problem is that the addon doesnt play the torrent! im using imac
log https://pastebin.com/Zqsig0SY

**Comment by Pinhastest** [comment] 2018-12-01 15:11
Is not possible to add .torrent or magnet links on Kodi Leia

**Comment by elgatito** [comment] 2018-12-02 20:08
Please, try version 0.0.66.

**Comment by elgatito** [comment] 2018-12-11 08:45
Fixed by 0.0.66.

**Closed by elgatito** 2018-12-11 08:45 UTC
