### ISSUE TITLE
Elementum daemon crashes when playing last episode of a season (nil deref error)

### ISSUE THREAD

**Issue by WurdahMekanik** [elgatito/plugin.video.elementum#904] opened 2023-03-11 05:30 UTC
## Expected Behavior

Elementum daemon should not crash.

## Current Behavior

If the episode playing is the last one in a season, the Elementum daemon consistently crashes when the video starts playing after a successful torrent download. In the specific case I see this issue, more episodes are actually planned for the season, but they are unaired as of yet. I have a feeling this last part is particularly relevant to this bug.

## Possible Solution

In the context below, there appears to be a nil deref runtime error in the Go code for the Elementum daemon itself. I'm an embedded systems dev, so Go isn't a language I'm familiar with, but it would appear to me from the segfault info below & looking into the daemon code a bit that tmdb.go:779 needs a nil check. I'd guess probably something like `if e != nil && e.EpisodeNumber == episode`

## Steps to Reproduce (for bugs)

I'm hoping the behavior description + segfault info is enough context...

## Context

warning <general>: [plugin.video.elementum] panic: runtime error: invalid memory address or nil pointer dereference
warning <general>: [plugin.video.elementum] [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xd9ad02]
warning <general>: [plugin.video.elementum]
warning <general>: [plugin.video.elementum] goroutine 13679 [running]:
warning <general>: [plugin.video.elementum] github.com/elgatito/elementum/tmdb.(*Season).HasEpisode(...)
warning <general>: [plugin.video.elementum]     /go/src/github.com/elgatito/elementum/tmdb/tmdb.go:779
warning <general>: [plugin.video.elementum] github.com/elgatito/elementum/bittorrent.getNextShowSeasonEpisode(0xc00033ed25?, 0xa, 0x3)
warning <general>: [plugin.video.elementum]     /go/src/github.com/elgatito/elementum/bittorrent/player.go:1456 +0x142
warning <general>: [plugin.video.elementum] github.com/elgatito/elementum/bittorrent.(*Player).processUpNextShow(_)
warning <general>: [plugin.video.elementum]     /go/src/github.com/elgatito/elementum/bittorrent/player.go:1296 +0x259

## Your Environment

* Version used: v0.1.87

* Environment name and version: Kodi v20

* Operating System and version: Linux x86-64

* Link to Kodi debug log: (see above)

**Comment by elgatito** [comment] 2023-05-31 14:17
I guess that is caused by TMDB, not able to communicate with.

**Comment by elgatito** [comment] 2023-07-01 11:11
Should be fixed in v0.1.88.

**Closed by elgatito** 2023-07-01 11:11 UTC
Labels: bug
