### ISSUE TITLE
Elementum is crashing when trying to Add Torrent

### ISSUE THREAD

**Issue by StevePet789** [elgatito/plugin.video.elementum#903] opened 2023-03-01 00:01 UTC
When I'm trying to add a torrent from a file, and starting to navigate through the file source, elementum crashes. Using Kodi 20

**Comment by 60secondsassassin** [comment] 2023-03-11 10:18
Same issue on my side with Kodi 20

Attached log below
[kodi.old.log](https://github.com/elgatito/plugin.video.elementum/files/10948242/kodi.old.log)

**Comment by icarok99** [comment] 2023-07-23 14:29
Yes, it seems it only happens on Android ARM64.

I have a stick tv Android ARM and it works perfectly.

**Comment by elgatito** [comment] 2023-07-27 10:40
It can be caused by libtorrent library and the system calls it does when adding torrent.

**Comment by elgatito** [comment] 2023-07-27 10:44
Btw, can you select Android Arm architecture, instead of automatic selection (that selects arm64)? Then restart Kodi and check again the issue.

**Comment by icarok99** [comment] 2023-07-28 13:17
![Screenshot_2023-07-28-10-16-53-954_org xbmc kodi](https://github.com/elgatito/plugin.video.elementum/assets/46580318/a42511df-f5a4-4f91-a48b-f97844de45ef)

**Comment by elgatito** [comment] 2023-07-28 13:19
@icarok99 Can you show the log when you run with Android Arm architecture selected?

**Comment by icarok99** [comment] 2023-07-28 13:38
@elgatito [Kodi log](https://drive.google.com/file/d/1-1w_jRbO_ZOpbqrgRrF4-AKmSsPttH-v/view?usp=drivesdk)

**Comment by elgatito** [comment] 2023-07-28 13:45
@icarok99 You log is saying you are running `android_arm64` platform, and not `android_arm`.

**Comment by icarok99** [comment] 2023-07-28 13:47
This problem only happens Android_arm64

**Comment by icarok99** [comment] 2023-07-28 13:57
On my other device which is Android_arm it is working normally 

![IMG_20230728_105438](https://github.com/elgatito/plugin.video.elementum/assets/46580318/7024fb26-6a35-45f0-acfb-c7df40d15b20)

**Comment by icarok99** [comment] 2023-08-03 12:20
@elgatito Problem solved with this new update, and thank you very much elgatito.

![Screenshot_2023-08-03-09-16-25-296_org xbmc kodi](https://github.com/elgatito/plugin.video.elementum/assets/46580318/bd59c76c-4d71-4394-a105-342e15e3da9b)

**Comment by elgatito** [comment] 2023-08-24 15:38
Great to hear. Closing the issue.

**Closed by elgatito** 2023-08-24 15:38 UTC
