### ISSUE TITLE
Elementum is sending payload with inconsistent episode numbers

### ISSUE THREAD

**Issue by movianlost** [elgatito/plugin.video.elementum#768] opened 2021-05-28 15:30 UTC
Elementum is sending payload with inconsistent episode numbers.

The below example is for an anime called "Doraemon", but this is not limited to only this anime, there are other anime that suffer from the same issue.
Here is an example of what I click on and what Elementum sends.
The first is the episode I click on -> this is what Burst receives, I notice the value of absolute_number in the payload

```
S25E9->S25E9 payload has absolute_number:0
S25E10->S25E1704 payload has absolute_number:1704

S24E9->S24E1658 payload has absolute_number:1658
S24E10->S24E10 payload has absolute_number:0
S24E11->S24E1660 payload has absolute_number:1660
```
Here is the log from the moment I started testing.
I clicked on S25E9 then S25E10

https://pastebin.com/raw/PWc5anzN

**Comment by antonsoroko** [comment] 2021-05-28 16:52
and what is expected behavior for this anime? S25E10 or S25E1704?

(also looks like tvdb does not have absolute_number for S25E9 so it is 0).

**Comment by movianlost** [comment] 2021-05-28 22:02
@antonsoroko  I think the problem here is that elementum takes the season and episode number from TMDB and try to use that to get the absolute number from TVDB, the problem arises when there is a disagreement between TMDB and TVDB which is quite often.

For my use case, I'm developing my own Elementum Burst alternative, which takes the payload from Elementum and returns the links to Elementum. So I want TMDB raw data without any modification to be used.

Can  you add an option in Elementum that doesn't change the season/episode number of an item and send the payload as it is used in TMDB?

You can an option in Elementum setting that enable/disable this. So if this option is enabled, Elementum shouldn't convert any season/episode combination to an absolute number, it should send the payload with the original season/episode number that it found from TMDB.

**Comment by antonsoroko** [comment] 2021-05-28 23:34
@movianlost 

1. can you plz answer this first?
>and what is expected behavior for this anime? S25E10 or S25E1704?

b/c i guess some anime uses absolute numbers and some not. just want to understand what is your case.
i mean - so far you have not described the reason of your issue. what exact numbers are causing your issue (10 or 1704).

2.
> Elementum takes the season and episode number from TMDB and try to use that to get the absolute number from TVDB, the problem arises when there is a disagreement between TMDB and TVDB which is quite often.

from the code i have seen - elementum just takes absolute_number from TVDB if it is exist (or from TMBD if it is exist, but this is rare case). i do not see any "disagreement" here. data either exist in source (TMBD/TVDB) or not. elementum does not do any calculations as far as i can see.

3.
>Can you add an option in Elementum that doesn't change the season/episode number of an item and send the payload as it is used in TMDB?

elementum does **not** change season/episode number. you can see this even in you own log file. for anime elementum **adds** absolute_number, and burst uses it. but in your own provider you are free not to use it.

example from you log file
```
2021-03-29 15:23:38.966 T:1262478208   DEBUG: [script.elementum.burst] Searching with payload (episode): 
{u'tvdb_id': 252696, -->u'episode': 9<--, u'silent': False, ...
u'title': u'doraemon', u'season': 25, ..., u'anime': True, u'absolute_number': 0, u'show_tmdb_id': 57911, u'skip_auth': False}
```
```
2021-03-29 15:23:44.639 T:1350562688   DEBUG: [script.elementum.burst] Searching with payload (episode): 
{u'tvdb_id': 252696, ---->u'episode': 10<---, u'silent': False, ..., 
u'title': u'doraemon', u'season': 25, u'proxy_url': u'', u'year': 2003, u'imdb_id': u'tt0069576', u'tmdb_id': 1171918, u'anime': True, u'absolute_number': 1704, u'show_tmdb_id': 57911, u'skip_auth': False}
```

**Comment by movianlost** [comment] 2021-05-29 15:35
> b/c i guess some anime uses absolute numbers and some not. just want to understand what is your case.
i mean - so far you have not described the reason of your issue. what exact numbers are causing your issue (10 or 1704).
The issue is the inconsistency, for each anime, it should stick to either use absolute_number for all episodes or user normal numbers for all episode. In the case of this anime "Doraemon" since some episodes don't have absolute_number, then the entire show should use normal episode number and not absolute_number.

I know Elementum uses TMDB for the data that it displays in its interface, like the tv show description,name, season and episode number, the solution to the problem above is to only rely on TMDB data for anime, and use the episode number used by TMDB without converting them to absolute_number because TMDB already uses the absolute_number by default for long running old anime and uses normal episodes for new anime.



>elementum does not change season/episode number. you can see this even in you own log file. for anime elementum adds absolute_number, and burst uses it. we can add such option to burst, but first we need answer for question number 1.

If I understand you correctly, can you add the option where I can access the non absolute_number of an anime episode in Burst? If that's the case, then that would solve my problem.
The writer of the provider can choose whether to use `{episode}` or `{normal_episode}` in the anime_keywords of the provider. where `{episode}` here will use absolute_number whereas `{normal_episode}` will always use the normal episode number.

>but in your own provider (if you by provider you really mean alternative to burst and not a new tracker for burst. in log file i only see burst and some modified version of 1337 tracker) you are free not to use absolute_number.

Yes in the log I was just modifying burst for testing. But I meant Burst alternative as in a new add-on not just a provider for Burst.
You said I'm free not to use absolute_number, if this is possible with Burst then I wouldn't need to develop my own add-on because I only thought of creating my own add-on because I couldn't get the non absolute_number of anime episodes. 
Is it possible to access non absolute_number in Burst?

**Comment by elgatito** [comment] 2021-05-29 19:19
There are separate fields coming from Elementum. `episode` + `absolute_number`.
In Burst `episode` is replaced by `absolute_number` if later is available.

**Comment by elgatito** [comment] 2021-05-29 19:50
@antonsoroko @movianlost 
I have pushed a commit to Burst repo to use `absolute_episode` in queries to insert absolute episode number. If number is not available - query will be skipped (will not search for `absolute_episode=0`).
It would be good to overview all providers if `absolute_episode` should be used somewhere. 
It seems we always search S{season}E{episode}, so I don't think absolute number should be used in that query. Maybe worth adding `E{absolute_episode}` or something like that, probably, each provider needs changes.

**Comment by movianlost** [comment] 2021-05-29 21:57
@elgatito That's a great solution and it fixed my problem, everything works fine now.
Introducing a separate variable {absolute_episode} is great, and provider's writers can choose whether to use it or not.
Currently, I don't think there is a need to update the providers because TMDB knows when to use absolute number and when not to, so by using {episode} which is the default in anime searches, it will use the episode number used by TMDB which is sometimes an absolute number if the show is an old running anime or just normal number if it's not.

**Comment by antonsoroko** [comment] 2021-05-30 08:44
https://github.com/elgatito/script.elementum.burst/commit/8a6ca293405d8a3341e7ac0a2778a748f0c90f9d

nice.
so @movianlost can add `{absolute_episode}` to anime providers if needed (if there is a case for queries with absolute number).

i guess we can close this? and also https://github.com/elgatito/script.elementum.burst/issues/265

**Comment by movianlost** [comment] 2021-05-30 11:49
@antonsoroko yes, both issues are solved and should be closed.

**Closed** 2021-05-30 11:49 UTC
