### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by Buildtexts69** [elgatito/plugin.video.elementum#1075] opened 2024-10-11 01:09 UTC
Can you clear up a couple things for me?
1- Everything says development has stopped, but the last update was 3 days ago. I assume this is not the case anymore?
2-I see the pinned issue about Trakt Sync, but its from 2020. Is this still an issue or not?
I assume its ok to authorize Trakt through the addon now correct? So that brings me to my main question..  When authorizing Trakt after entering the code, Elementum notifies that Trakt has been successfully authorized, however the authorization screen does not go away after authorizing. If you hit OK or back a message comes up saying Trakt authorization cancelled. But after opening it seems it is authorized. Is this just a small bug with the auth window not going away? Is it OK now to use Trakt with Elementum???

**Comment by antonsoroko** [comment] 2024-10-11 14:15
@Buildtexts69 
1. so it should be read as "**Active** development is stopped", bug fixes are still coming, some small features are still coming from author and other users. but if someone wants some big feature to be implemented - then this someone should implement it by himself/herself.
i asked @elgatito to change the text long - https://github.com/elgatito/plugin.video.elementum/issues/536#issuecomment-2041155564 but maybe he have not seen it :-)

2. i do not think so. maybe @elgatito should finally close https://github.com/elgatito/plugin.video.elementum/issues/636

3. it is a bug. if "Elementum notifies that Trakt has been successfully authorized" - then all ok. for test you can add some movie to your watchlist, then you can navigate to movie->"trakt my watchlist" and see it.

**Comment by elgatito** [comment] 2024-10-11 14:34
@Buildtexts69 if you think there is a bug with Trakt sign in - please, make a log file and report it.

**Comment by antonsoroko** [comment] 2024-10-11 14:36
@elgatito there is a bug, i also have seen it back in time. i made a fix.

also, it would be nice to fix point 1 and 2 :-)

**Comment by Buildtexts69** [comment] 2024-10-14 12:43
> @elgatito there is a bug, i also have seen it back in time. i made a fix.
> 
> also, it would be nice to fix point 1 and 2 :-)

Thank-You!

**Comment by elgatito** [comment] 2024-10-18 13:12
Closing the issue.

Duplicate of #536

**Closed by elgatito** 2024-10-18 13:12 UTC
