### ISSUE TITLE
[Bug] Seasons/Episodes not always translated

### ISSUE THREAD

**Issue by dancaer69** [elgatito/plugin.video.elementum#284] opened 2018-12-03 11:00 UTC
Why in elementum seasons/episodes of series displayed transalted to my local language instead of native language?
This is how are listed the seasons/episodes for a series in elementum:

---------------------------------------------------------------------------
 series: 
    12 Monkeys       (the title isn't translated)
         4η σαιζόν
              Επεισόδιο 1
              Επεισόδιο 2
              ...
         3η σαιζον
              Επεισόδιο 1
              Επεισόδιο 2
              ...
         2η σαιζόν
              Επεισόδιο 1
              Επεισόδιο 2
              ...
         1η σαιζόν
              Επεισόδιο 1
              Επεισόδιο 2
              ...
--------------------------------------------------------------------------
Those are the seasons/episodes of the series translated to greek. And those info are wrong because normaly should be the episodes title for every episode and not the word "episode" translated. 
And this doesn't change even if I change the language in kodi to engish. I tested and in a new kodi installation with only elementum installed. I also have set TVDB and TMDB to use english language.
Is there any way to change this?

**Comment by dancaer69** [comment] 2018-12-03 15:34
The problem is that, no matter what I do I don't see English. I have changed every related setting I found.. Where is the "use Trakt if available" option? I only found in elementum settings trakt section the "Use Trakt information in Trakt lists" option which I already have checked.

**Comment by elgatito** [comment] 2018-12-03 17:33
Video was helpful. Thanks
Looks I've found a bug and it will be fixed in the next version.

**Comment by elgatito** [comment] 2018-12-16 11:11
Please, try 0.0.67.

**Comment by dancaer69** [comment] 2018-12-16 13:49
I just tried 0.67. I get an error when tried to open trakt collection(or anything related to trakt). After I cleared caches and reauthorise trakt, trakt collection etc was available again. But the update didn't make any difference. I still have the same issue as described above.

**Comment by elgatito** [comment] 2018-12-16 14:00
I can't reproduce the issue, as it was in the video.

**Comment by dancaer69** [comment] 2018-12-16 14:14
Maybe, it is because I have now setted language to Greek and not English. But I other addons(like the one on the video), I have no problem no matter if I have set interface language Greek or English. I will try to set interface language to English and test it again later.

**Comment by dancaer69** [comment] 2018-12-16 17:38
I just test it and with English inteface language(after kodi restart) I have the english titles for episodes too, but with Greek inteface language I just have the translated "episode" word, with the number of episode, as I mentioned above. This doesn't happen with other addons in which titles of series, seasons and episodes are in english, no matter the interface Language, as it should. This leads to other troubles. For e.g I cannot use kodi's trakt context menu to toggle manually an episode as watched, because it cannot find an episode with such a title, which is expected because searches for the original title of the episode and not the translated word episode followed with the number of the episode.

**Comment by elgatito** [comment] 2018-12-16 17:58
>  I just have the translated "episode" word, with the number of episode

It's returned by TheMovieDB, not composed by Elementum.

> For e.g I cannot use kodi's trakt context menu to toggle manually an episode as watched, because it cannot find an episode with such a title, which is expected because searches for the original title of the episode and not the translated word episode followed with the number of the episode.

If you have enabled Trakt in Elementum - it will set episode as watched in Trakt. It does not need any title.

**Comment by dancaer69** [comment] 2018-12-16 18:12
Is there any way to use TVDB which seems to be more friendly to non english languages and is more complete for TV series? For example the "The Ranch" series the last time I checked had 3rd season incomplete(displayed only 10 from 20 episodes), and at the same time addons which use TVDB had them all.
As for Trakt, I know that, but sometimes I need to use this option to manually set an episode, or a season as watched.

**Comment by elgatito** [comment] 2018-12-17 09:34
> Is there any way to use TVDB which seems to be more friendly to non english languages and is more complete for TV series?

No. It's a big work to add TVDB and use it. And it will slow whole application a lot. It does not cost that, for getting episode names.

**Comment by elgatito** [comment] 2018-12-17 09:37
This issue was first reported about missing translations at few locations of Elementum (browsing inside of a plugin). Which is fixed now.
We do not modify or compose names for seasons/episodes.

**Closed by elgatito** 2018-12-17 09:37 UTC
Labels: bug

**Comment by dancaer69** [comment] 2018-12-17 15:35
What is fixed? As I said above, I don't see any difference. I have the same problem as before with 0.67 version. I don't know what causes the problem. I just know that on other addons the episode titles displayed in english(since there is not translation to the language I use) as it should. In elementum just the word "episode" translated, and not for all series and episodes. I asked about TVDB because there aren't any such problems there. If it's too difficult and doesn't worht it, it's ok. But maybe you can add an option to prevent the translations and keep the original(usually english) language. I think I have seen this kind of option in other addons. Didn't need it it though, because if there is no translation for episode titles the displayed in english by default.
