### ISSUE TITLE
Trakt not syncing new tv shows to library

### ISSUE THREAD

**Issue by mospre** [elgatito/plugin.video.elementum#275] opened 2018-11-20 17:53 UTC
I thought it was problem on my side, then I did fresh install on two other devices, movies from trakt sync perfectly but tv shows do not. I can't see them in library, just blank tab..

**Comment by elgatito** [comment] 2018-11-21 12:36
There is a clear requirement to include a log file. http://elementum.surge.sh/contribute/log/
Which show?
How you update?
How you add to the library?
Physically no new episodes strm files created?
Is it available on TheMovieDB?

**Comment by mospre** [comment] 2018-11-21 22:06
Funny thing is that movies are scraped perfectly. Only different thing i can notice is when movies are being scraped that on top right corner says movieName.strm, before it said just movieName without extension. Sorry for bad english. 

Thanks for tast answers and best streaming addon!

**Comment by elgatito** [comment] 2018-11-22 07:39
It is caused by Tvdb scrapper, that does not correctly scrape NFO files.
I will add option to skip NFO creation, but you still have to delete existing nfo files manually if you want to use Tvdb scraper. Or you can switch to TheMovieDB series scraper.

**Comment by jesus225** [comment] 2018-11-22 08:09
Thanks. Do you know if this is a recent change by Tvdb add-on or elementum? A month ago I was able to scrap with the same settings with no issues so wondering what caused the problem.

**Comment by elgatito** [comment] 2018-11-22 20:19
@jesus225 have no clue. NFO files are created not the first month, maybe something changed in Tvdb scraper.

**Comment by elgatito** [comment] 2018-11-23 19:00
I have added option to disable NFO files for Movies/Shows. You can disable it and remove NFO files. Or switch to TheMovieDB.

**Comment by Jezze83** [comment] 2018-11-29 18:51
@elgatito elementum wont sync new seasons from trakt anymore. I just disabled that nfo setting, is that solution for that? Do i need manually remove all nfo files?

**Comment by elgatito** [comment] 2018-11-29 18:52
@Jezze83 everything is working fine with the last version. Even with TVDB. Just remove whole directory and let it recreate strm files.

**Comment by elgatito** [comment] 2018-11-29 18:54
/Shows directory, created by Elementum, or specific show directory.

**Comment by elgatito** [comment] 2018-11-30 11:33
Should I close this?

I have tried to remove Shows directory (created by Elementum) and re-sync Trakt and I've got everything with TVDB.

**Comment by elgatito** [comment] 2018-12-11 08:30
TVDB scraping should work fine with the latest TVDB addon.

**Closed by elgatito** 2018-12-11 08:30 UTC
