### ISSUE TITLE
Elementum crashes after several seconds of playback.

### ISSUE THREAD

**Issue by Fluttercom** [elgatito/plugin.video.elementum#443] opened 2019-06-02 20:13 UTC
Elementum starts crashing after about 30s of playback. Tried to clear db and reinstall. Any file.

## Steps to Reproduce (for bugs)
1. Select any torrent
2. Start play
3. Wait a minute

## Your Environment
Kodi
* Version used:
0.1.32
* Environment name and version:
Kodi 17.6
* Operating System and version:
LibreElec 8.2.5
* Link to Kodi debug log:
https://paste.kodi.tv/jepuvudora
https://paste.kodi.tv/todolucusi

**Comment by elgatito** [comment] 2019-06-03 06:10
Seeing the same with linux_armv7 architecture. 
Probably caused by Musl usage.

**Comment by elgatito** [comment] 2019-06-03 19:44
Please, try with 0.1.33.

**Comment by Fluttercom** [comment] 2019-06-03 19:48
Now it doesn't start to play at all (constant loading screen).

**Comment by elgatito** [comment] 2019-06-03 21:13
@Fluttercom please, try to reinstall from repository version 0.1.33.

**Comment by elgatito** [comment] 2019-06-10 11:42
Should be fixed with v0.1.35.

**Closed by elgatito** 2019-06-10 11:42 UTC
