### ISSUE TITLE
Option to have subtitles saved

### ISSUE THREAD

**Issue by sveltosss** [elgatito/plugin.video.elementum#128] opened 2018-03-23 09:49 UTC
Hi.

Thank you for your great effort to this project.

Is it possible to add an option to have subtitles saved together with the movie file?
This is useful if you want to keep the downloaded file and play it again or if you want to play the file with an external player

Thank you.

**Comment by sveltosss** [comment] 2018-05-08 07:25
Yes, but if I stop the playback and open the file with kodi (not from within elementum) the subtitle is saved next to the video file. This does not happen with elementum. There is not downloading of subtitle taking place. I can see that by pausing the video playback and browsing to the directory where the video file resides.

**Comment by elgatito** [comment] 2018-05-08 07:29
that is because you open already-downloaded file locally and Kodi can save there subtitles. While you open from Elementum - you stream file to Kodi, like from an internet, so it can't do anything with it, Kodi does not even know when the file is saved.

**Comment by sveltosss** [comment] 2018-05-08 07:32
Ok I see. But when I choose to download a subtitle (while playing video from within elementum), is it put in memory by kodi? Does Kodi stream the subtitle as well? Isn't it stored somewhere even temporarily?

**Comment by elgatito** [comment] 2018-05-08 11:47
Sorry, I don't know how Kodi treats subtitles files. They are pretty small, so easily can be stored in memory.

**Comment by elgatito** [comment] 2018-05-14 04:38
duplicate of #137

**Closed by elgatito** 2018-05-14 04:38 UTC
