### ISSUE TITLE
Daemon stop immediately after start on 0.0.70 (nvidia shield tv)

### ISSUE THREAD

**Issue by viktoraseev** [elgatito/plugin.video.elementum#309] opened 2018-12-23 18:08 UTC
Daemon doesn't doesn't respond or crash just after the start. Plugin tries to restart it several times and finally stops.
As result, dialog ' упс перезапуск' appears 3 times, then addon stops.
Fresh system install, only KODI 0.17.x is installed.
Version: 0.0.70
Platform: Nvidia Shield TV

## Steps to Reproduce (for bugs)
Install Kodi 17
Install Elementum 0.0.70 (tried versions arm64 or all-in-one)
Observe error.

## Your Environment
Fresh system, Nvidia Shield TV.

log https://pastebin.com/XLNgBNNK

Update: tried plugin.video.elementum-0.0.68.android_arm64.zip - doesn't work as well

**Comment by elgatito** [comment] 2018-12-23 20:46
You get settings windows when it tries to start?
Try to change downloads and library path to other directory, maybe your android is too much secure.

**Comment by viktoraseev** [comment] 2018-12-24 08:40
Settings window doesn't appear. Just messages in a top corner about daemon error and restarting.
My android is latest 8.0 android tv. This evening I'll try to change folders to another location and post results.

One of the problems here is that crash stacktrace is not visible in a log. Probably it is logged into stderr, which doesn't go into log. Any ideas how to fix that? I see params 'stderr': -2, 'stdout': -1 in a daemon start args, probably changing this may help. But I dont know what exactly is this and how to change these params.

**Comment by elgatito** [comment] 2018-12-24 08:48
Yes, I don't see any error in the log file, as well. 
Like the binary was killed by system. 
Kodi debug mode is enabled, right? 
I guess you don't have some kind of a process manager or killer?

**Comment by viktoraseev** [comment] 2018-12-24 09:05
Yes, debug is enabled(all the settings on a page), also, I think I see some debug logs from daemon. 
Like this:
`19:28:28.613 T:177743054064  NOTICE: [plugin.video.elementum] INFO  main         ▶ main             [0mStarting Elementum daemon
19:28:28.613 T:177743054064  NOTICE: [plugin.video.elementum] INFO  main         ▶ main             [0mVersion: 0.0.70 GoTorrent: cc531b8c Go: go1.11.4, Threads: 4
...`
But crash is not visible.

About manager or killer: I have installed ES Manager(default configuration), but I don't think it kills app. Nothing else is installed.

Can this be an OOM kill? my config have 3GB of memory, but how knows? I will try this: https://stackoverflow.com/questions/726690/what-killed-my-process-and-why

Any ideas about strerr? How to check if it actually goes to log and how to change these values -1/-2?

**Comment by elgatito** [comment] 2018-12-24 09:10
> I think I see some debug logs from daemon.

Yes, it starts to load and then just stop, every time in different places.

> Any ideas about strerr? How to check if it actually goes to log and how to change these values -1/-2?

No, I don't know. stderr/out is intercepted by python code of plugin and then logged to Kodi.

You can try to start binary manually from shell or any other way, just

**Comment by elgatito** [comment] 2018-12-25 14:59
Can you make another log after reboot/restart?

**Comment by viktoraseev** [comment] 2018-12-25 17:15
I managed to run plugin after changing folders from defaults to /downloads. Works perfectly. Are you still interested in logs after reboot? I believe that will change nothing. Real issue is that such kind of crashes doesn't go into the log.

**Comment by rxin** [comment] 2018-12-30 02:04
How do I get to settings for Elementum if it cannot start?

**Comment by ssarava9** [comment] 2019-01-08 15:21
@viktoraseev can you give me exact download path you set in your device ?

I tried both the below path for windows and android and still getting "download path not set, check setting" error everytime

Windows:
C;\temp\downloads\  or E:\downloads or C:\users\app data\roaming\kodi\temp\downloads etc

Android:
/storage/android/data/org.xbmc.kodi/files/downloads

Please help

**Comment by viktoraseev** [comment] 2019-01-08 18:32
All the paths are set to /storage/emulated/0/Download/

**Comment by elgatito** [comment] 2019-01-10 12:50
@viktoraseev it started to work after you changed empty default Download path? Or after you changed another path? 
I can't reproduce your bug, so trying to find which setting is causing your issue.

**Comment by elgatito** [comment] 2019-03-23 20:22
Closing. This should be fixed in latest versions.

**Closed by elgatito** 2019-03-23 20:22 UTC
