### ISSUE TITLE
can't remove movie from elementum library

### ISSUE THREAD

**Issue by shmizan** [elgatito/plugin.video.elementum#606] opened 2020-07-01 17:09 UTC
I'm working with elementum's great trakt sync.
I sync my trakt watchlist into my Kodi library.
when I finished watching a movie, the trakt entry for that movie is automatically removed from the watchlist, but the movie remains in my library.
I tried to delete the folder that contains this movie in .kodi/temp/elementum_library/Movies, and to use "Remove from library" in the movie's context menu and "manage...", but it keeps coming back (presumably from the backup elementum makes from the db).

what is the correct way to remove items from the elementum library?

thanks!

**Comment by elgatito** [comment] 2020-11-17 10:49
@shmizan duplicate of #509

**Closed by elgatito** 2020-11-17 10:49 UTC
