### ISSUE TITLE
Upload is enabled but stays on 0kb/s

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#391] opened 2019-03-18 00:41 UTC
I enable the upload and set it to 1000kb/s limit.
But when I checked it, the downloading was ok but the uploading was staying on 0kb/s

Why is that?

Kodi Log:
https://paste.ubuntu.com/p/jNsKQmyH8N

Elementum 0.1.21
Kodi 17.6
Win 10, 64bit

**Comment by elgatito** [comment] 2019-03-19 20:19
Can't see anything special in the log.
Upload can't be disabled in libtorrent, only limited by speed. 

It shows status of torrent as seeding or finished?
Do you see any difference if you remove upload limit?

**Comment by burekas7** [comment] 2019-03-24 21:57
It seems to be ok now with 0.1.23 (or maybe it was a torrent with very low peers)

But there is another issue, why when the torrnet is reached to 100%, the status over the playback say it's "seeding" and there is uploading (Not shoud be like that) , while the status in the Torrents list is "Finished" as it should be (And the background status notification is closed also as it should be)
As I remeber when it reached to 100% it should stop seeding and the upload rate is decrease to 0kb/s.

**Comment by antonsoroko** [comment] 2019-03-24 22:04
>and the upload rate is decrease to 0kb/s.

Why? For instance, i configured my elementum to seed for a long time, i am not greedy :-)

**Comment by burekas7** [comment] 2019-03-24 22:06
> > and the upload rate is decrease to 0kb/s.
> 
> Why? For instance, i configured my elementum to seed for a long time, i am not greedy :-)
I didn't know that it's an option, I think it's the default behaviour from Quasar, and it was like that also in Elementum until 0.1.23.

**Comment by burekas7** [comment] 2019-03-24 22:06
@elgatito 

I also want to use this issue to ask another question,how is it possible that I pause a torrent and then resume improve the download speed (regarding to a low torrent), from stable speed of 50kb/s after pause/resume torren get 1500kb/s and higher.

**Comment by antonsoroko** [comment] 2019-03-24 22:10
>, I thought it's the default behaviour from Quasar, and it was like that also in Elementum until 0.1.23.

there always were options about configuring how much time you want to seed - in quasar and then in elementum.

**Comment by burekas7** [comment] 2019-03-24 22:16
> > , I thought it's the default behaviour from Quasar, and it was like that also in Elementum until 0.1.23.
> 
> there always were options about configuring how much time you want to seed - in quasar and then in elementum.

Ok, probably I missed that, good to know.

By the way it seems that it's now uploading anymore and the upload is actually stopped now and show 0kb/s (Maybe it was leftovers from the remain uploads during the download).
But the status on the dialog in playback still show "Seeding" status instead of "Finished".

**Comment by antonsoroko** [comment] 2019-03-24 23:07
If it is not uploading and you have settings that says that it should - it is a bug (missing uploading) .
Btw, in my elementum old torrents in finished state and only new in seeding state.

**Comment by elgatito** [comment] 2019-03-25 12:10
@burekas7 

> status over the playback say it's "seeding"

You mean status that is shown when you pause player?

**Comment by elgatito** [comment] 2019-03-25 12:12
@burekas7 

> I also want to use this issue to ask another question,how is it possible that I pause a torrent and then resume improve the download speed (regarding to a low torrent), from stable speed of 50kb/s after pause/resume torren get 1500kb/s and higher.

There is nothing special in pause/resume, we pass that action to libtorrent. So it, probably, has some internal calls after we resume the torrent.

There were messages, in libtorrent repo, that pause/resume increases number of connections, thus I could not reproduce it. Pause/resume made even worst.

**Comment by elgatito** [comment] 2019-03-25 12:13
@burekas7 @antonsoroko 

> there always were options about configuring how much time you want to seed - in quasar and then in elementum.

Options to control seeding are described in Libtorrent documentation for settings. Look over `seed_ratio` and so on.

**Comment by burekas7** [comment] 2019-03-25 13:43
> 
> 
> @burekas7
> 
> > status over the playback say it's "seeding"
> 
> You mean status that is shown when you pause player?

Yes. (The overlay status)

**Comment by elgatito** [comment] 2019-03-26 21:04
@burekas7 should be fixed with 0.1.24.
There is also added optional Pause/Resume hack to settings. But I'm not sure it will work the same for you.

**Comment by burekas7** [comment] 2019-03-26 22:15
Thanks.

And what does the new setting mean? what does it do?

**Comment by elgatito** [comment] 2019-03-31 10:27
@burekas7 pause and then resume the torrent.

**Comment by burekas7** [comment] 2019-03-31 10:56
Understood.
But how does it know when to do this action of pause/resume?

**Comment by elgatito** [comment] 2019-03-31 13:28
@burekas7 After defining buffer size and needed pieces. I can place in other places if you have a proposal.

**Comment by burekas7** [comment] 2019-04-02 18:05
I think the problem still exist in 0.1.24

Upload is staying on 0kb/s even it's enable and limited to 1000kb/s (Download is also limited to 10000kb/s)

Basically it shows 1/6 or 1/3 (Peers) but maybe no one is actually connected to me?

p.s.
How can it be that the left number in Seeds is bigger than the right?

Two examples:
![image](https://user-images.githubusercontent.com/13424257/55425241-a09cf700-558a-11e9-886f-6ac8b8713dd2.png)
![image](https://user-images.githubusercontent.com/13424257/55425309-d215c280-558a-11e9-809b-e15c46c37470.png)

Kodi Log:
https://paste.ubuntu.com/p/xHY2ddV8dJ

**Comment by elgatito** [comment] 2019-04-02 19:58
> Upload is staying on 0kb/s

Upload speed is got from libtorrent.

> How can it be that the left number in Seeds is bigger than the right?

Numbers got from libtorrent.

Elementum is not limiting upload and not controlling it.

**Comment by burekas7** [comment] 2019-04-02 20:10
Quasar also using libtorrent right? And there is uploading value when using it.

**Comment by elgatito** [comment] 2019-04-02 20:19
> Quasar also using libtorrent right? And there is uploading value when using it.

1) Yes. But it includes traffic with peers.
2) It's almost 2 years old version of libtorrent. There are a lot of differences.

Still don't understand why don't you use Quasar.

**Closed by elgatito** 2019-04-02 20:19 UTC

**Comment by burekas7** [comment] 2019-04-02 20:28
Because Elementum is more organized, user friendly, updated and has better synchronization with Trakt.
Usually I'm using Quasar as a reference or as backup when I don't get well performance with the download or with connections in Elementum.

But thanks anyway.
