### ISSUE TITLE
Files not moving to selected folder after finishing download

### ISSUE THREAD

**Issue by patillerox** [elgatito/plugin.video.elementum#371] opened 2019-02-26 20:10 UTC
Hi! First of all, thanks for your awesome work with this addon! It's very useful for me :)

After a few problems with my SD card i installed all the system again (last version of OSMC over a Raspberry pi 3, and elementum 0.1.16). 

I was using Elementum for a few months before the broken SD card. Now i found that the finished torrents arent moving into the selected folder. They stay in the download folder, but never moves into his expected location

## Expected Behavior
I configured the addon to move the files into an USB folder after the torrent is finished.  

## Current Behavior
When the download is finished, the file stays in the folder when it was downloaded. It never moves into his expected folder. 

Any idea what could be happening? Maybe it's a bad configuration, but before i reinstalled the system it worked properly (i think i was using elementum 0.51) 

Thanks for your help and time! :)

## Your Environment
Raspberry Pi 3
* Version used:
0.1.16
* Environment name and version:
OSMC with Kodi 17.6

* Link to Kodi debug log:
https://paste.kodi.tv/ohahigovuh

**Comment by elgatito** [comment] 2019-03-03 14:34
Can't see it the log. Torrent was 100% downloaded?

**Comment by patillerox** [comment] 2019-03-03 18:16
Yes! it disappeared from the "torrents" section.

I moved the file manually and watched the film yesterday :)

you cant access the log? Do you want another log? :)

**Comment by elgatito** [comment] 2019-03-03 22:19
I can see the log, but I can't see that there was any attempt to move files. 
Probably it's not working.

**Comment by patillerox** [comment] 2019-03-04 20:23
In 0.0.71 happens the same. 

Do you have plans to fix it? :) It's useful for some users :)

**Comment by elgatito** [comment] 2019-03-04 21:00
> Do you have plans to fix it?

@patillerox yes, sure, but don't know when I'll have time.

**Comment by patillerox** [comment] 2019-03-05 19:00
Ok! Thanks! I'll look forward to it :)

**Comment by D4anielCB** [comment] 2019-03-08 23:56
It was working fine till some days it just not moving anymore, anyway i love your addon, ive tried a lot and your is the best, thanks for sharing this masterpiece

**Comment by elgatito** [comment] 2019-03-23 21:05
duplicate of #350

**Closed by elgatito** 2019-03-23 21:05 UTC
