### ISSUE TITLE
0.1.76 identified as having a virus   - Trojan:Win32/Zpevdo.B

### ISSUE THREAD

**Issue by kidkjbiker** [elgatito/plugin.video.elementum#739] opened 2021-04-08 03:03 UTC
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by kidkj77070** [comment] 2021-04-08 03:32
Went back and loaded 1.69. Seems ok.

**Comment by elgatito** [comment] 2021-04-08 06:29
There is no virus.
Duplicate of #728

**Closed by elgatito** 2021-04-08 06:29 UTC
