### ISSUE TITLE
Elementum timeout while "resolving torrent"

### ISSUE THREAD

**Issue by peerchemist** [elgatito/plugin.video.elementum#911] opened 2023-03-20 18:13 UTC
Running Android 12, Kodi v20.1, Elementum 0.1.87.

I've found relevant output in the log:

```
2023-03-20 17:44:47.867 T:6260  warning <general>: [script.elementum.burst] Providers returned 23 results in 3.57 seconds
2023-03-20 17:44:47.875 T:5868  warning <general>: [plugin.video.elementum] [GIN] 2023/03/20 - 17:44:47 | 200 |      631.75µs |       127.0.0.1 | POST     "/callbacks/7258755254777048948"
2023-03-20 17:46:32.032 T:5868  warning <general>: [plugin.video.elementum] INFO  library      ▶ updateLibraryShows  [0mLibrary updated in 128.333µs
2023-03-20 17:46:32.062 T:5837     info <general>: JSONRPC Server: New connection added
2023-03-20 17:46:32.073 T:5837     info <general>: JSONRPC Server: Disconnection detected
2023-03-20 17:46:32.088 T:6422     info <general>: VideoInfoScanner: Starting scan ..
2023-03-20 17:46:32.097 T:5868  warning <general>: [plugin.video.elementum] [36mDEBU  main         ▶ Notification     [0mGot notification from xbmc/VideoLibrary.OnScanStarted: null
2023-03-20 17:46:43.972 T:6257    error <general>: Traceback (most recent call last):
                                                   
2023-03-20 17:46:43.972 T:6257    error <general>: 
2023-03-20 17:46:43.975 T:6257    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 333, in run
                                                       data = _json(url)
                                                              ^^^^^^^^^^
                                                   
2023-03-20 17:46:43.975 T:6257    error <general>: 
2023-03-20 17:46:43.975 T:6257    error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/navigation.py", line 193, in _json
                                                       with closing(urllib_request.urlopen(url)) as response:
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2023-03-20 17:46:43.975 T:6257    error <general>: 
2023-03-20 17:46:43.975 T:6257    error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
                                                       return opener.open(url, data, timeout)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2023-03-20 17:46:43.975 T:6257    error <general>: 
2023-03-20 17:46:43.975 T:6257    error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py", line 519, in open
                                                       response = self._open(req, data)
                                                                  ^^^^^^^^^^^^^^^^^^^^^
                                                   
2023-03-20 17:46:43.975 T:6257    error <general>: 
2023-03-20 17:46:43.975 T:6257    error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py", line 536, in _open
                                                       result = self._call_chain(self.handle_open, protocol, protocol +
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2023-03-20 17:46:43.975 T:6257    error <general>: 
2023-03-20 17:46:43.975 T:6257    error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
                                                       result = func(*args)
                                                                ^^^^^^^^^^^
                                                   
2023-03-20 17:46:43.975 T:6257    error <general>: 
2023-03-20 17:46:43.975 T:6257    error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py", line 1377, in http_open
                                                       return self.do_open(http.client.HTTPConnection, req)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2023-03-20 17:46:43.975 T:6257    error <general>: 
2023-03-20 17:46:43.975 T:6257    error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/urllib/request.py", line 1352, in do_open
                                                       r = h.getresponse()
                                                           ^^^^^^^^^^^^^^^
                                                   
2023-03-20 17:46:43.975 T:6257    error <general>: 
2023-03-20 17:46:43.975 T:6257    error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 1374, in getresponse
                                                       response.begin()
                                                   
2023-03-20 17:46:43.975 T:6257    error <general>: 
2023-03-20 17:46:43.975 T:6257    error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 318, in begin
                                                       version, status, reason = self._read_status()
                                                                                 ^^^^^^^^^^^^^^^^^^^
                                                   
2023-03-20 17:46:43.975 T:6257    error <general>: 
2023-03-20 17:46:43.975 T:6257    error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/http/client.py", line 279, in _read_status
                                                       line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2023-03-20 17:46:43.976 T:6257    error <general>: 
2023-03-20 17:46:43.976 T:6257    error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/socket.py", line 706, in readinto
                                                       return self._sock.recv_into(b)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2023-03-20 17:46:43.976 T:6257    error <general>: 
2023-03-20 17:46:43.976 T:6257    error <general>: TimeoutError: timed out
```

I've tried setting google DNS, system-wide. Same result.

**Comment by slavatyn** [comment] 2023-03-24 04:24
Have same issue on mobile devices, tablet and phone android 13, but all OK on Google TV.
After choosing film and it's fiend some torrents , going messege (checking torrent file 0%) and it's stuck.

**Comment by misterti** [comment] 2023-04-25 13:15
Same problem here on Android 13

**Comment by elgatito** [comment] 2023-05-31 14:14
Looks like binary is silently killed by system (or has a segfault inside).
It is hard to debug such issues.
Does it reproduce on any Android 13 device? (like Pixel phone or Pixel tablet)

**Comment by slavatyn** [comment] 2023-06-01 06:59
I have an Android 13 tablet and I'm wondering if there's a way for me to assist with log files, even though I don't have any experience with Logcat?
I apologize if this is a basic question. If I can't help, feel free to ignore my message.

**Comment by StefanIlchev** [comment] 2023-06-01 20:14
@elgatito 

> When I install x86 emulator of Android 13 - I cannot run Kodi (it says platform x86 is not supported).

They don't seem to make x86(_64) builds anymore.

> When I install armv8 elumator - it cannot start saying QEMU2 cannot use armv8 on current platform.

Those are for ARM devices such as Chromebooks and M-series Macbooks.

On an x86 PC you'd need an x86(_64) emulator that supports ARM ABIs such as those for Android TV and Google TV. You could check and see if you can find more but I don't know of any others.

**Comment by elgatito** [comment] 2023-06-02 15:03
Strange. I have managed to install Kodi APK for x86, same 20.1 version as on the phone - https://mirrors.kodi.tv/releases/android/x86/ .
It runs fine and Elementum runs fine.

While on the phone when window with buffering progress opens - it stays empty all the time.
Like there are python differences.

**Comment by elgatito** [comment] 2023-08-30 12:42
@slavatyn Can you try the latest 0.1.97 version?

**Comment by slavatyn** [comment] 2023-09-07 18:22
Same on 2 devices( 
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/12552316/kodi.log)

**Comment by slavatyn** [comment] 2023-09-07 18:23
[kodi.log](https://github.com/elgatito/plugin.video.elementum/files/12552318/kodi.log)

**Comment by antonsoroko** [comment] 2023-09-12 12:31
@slavatyn your log file does not show any error or timeout. On the contrary:
```
▶ bufferTickerEvent  [0mBuffer. Pr: 2%, Sp: 154 kB / 0 B, Con: 9/9 + 0/37, Pi: [0:0, 1:0, 2:0, 3:0, 4:0, 1509:17, 1510:0]
▶ bufferTickerEvent  [0mBuffer. Pr: 14%, Sp: 691 kB / 0 B, Con: 12/13 + 0/35, Pi: [0:0, 1:0, 2:0, 3:0, 4:0, 1509:75, 1510:25]
```


in your settings:
`2023-09-07 21:05:47.629 T:14526 warning <general>: [plugin.video.elementum]   BufferTimeout: 60,`

try to increase BufferTimeout in settings.

**Comment by elgatito** [comment] 2023-09-15 14:01
Closing this issue.
If there are any left issues - feel free to create a new issue.

**Closed by elgatito** 2023-09-15 14:01 UTC
