### ISSUE TITLE
[Bug] Episodes are added before Aired time

### ISSUE THREAD

**Issue by jorgecardoso220** [elgatito/plugin.video.elementum#98] opened 2018-02-09 09:49 UTC
Hi,

Normaly the addon adds, to the kodi library, the tv shows episodes on the day they are released, but we can only get torrents to see them the day after. 
There is any way to only add the episodes to the kodi library the day after they have been released?

thanks in advance,

**Comment by burrodesancho** [comment] 2018-02-09 10:24
It also happens to me. But only with tv shows that are not in my timezone (e.g. shows from US).

I have tried adding tmdb API to elementum. And I tried changing time zone in settings at tmdb website but the problem remains.

**Comment by elgatito** [comment] 2018-02-14 12:53
@jorgecardoso220 people fill aired date on TMDB, we check that field when getting episodes list. If you don't check "show unaired episodes" in plugin settings - you should not see that episode in the list.
But you don't know if the date is right, or is it filled in at all.

There are some changes to minimize this issue in the last version, so you can try it.

**Comment by jorgecardoso220** [comment] 2018-02-15 08:38
I think the addon is doing what it's suppose to do. But, since i only can see the episodes the day after their release, because it's when the torrents appear, there is any way to implement a feature to only add the episodes the day after the aired date?

**Comment by elgatito** [comment] 2018-02-15 08:42
@jorgecardoso220  Example of such show/episode?

**Comment by jorgecardoso220** [comment] 2018-02-15 08:51
For example, American Crime Story S02E05, the air date is14-02-2018 but i only can get torrents today, so 15-02-2018, but the episode was added to my kodi library 14-02-2018.
I would like the episode only been added 15-02-2018.

**Comment by elgatito** [comment] 2018-02-15 09:21
I have found the cause of this issue. It was because tmdb date, like "2018-14-02" was translated to "2018-14-02 00:00:00" was compared to current time, which, for example is "2018-14-02 00:00:01" and so it's always *after* current date. 

The fix will be added to the next version of plugin.

**Comment by jorgecardoso220** [comment] 2018-02-15 09:51
Thank you

**Comment by jorgecardoso220** [comment] 2018-04-20 13:31
Yes of course. soon i try it i will report

**Comment by jorgecardoso220** [comment] 2018-05-07 16:19
Any news on this issue?

**Comment by elgatito** [comment] 2018-06-19 06:04
I guess I have found the problem. We were letting episode which are aired "today". 
Will be fixed in the next version.

**Comment by elgatito** [comment] 2018-06-20 06:04
Should be better with v0.0.50.

**Comment by jorgecardoso220** [comment] 2018-07-06 17:10
It seems ok now. 

Thanks

**Closed** 2018-07-09 04:32 UTC
Labels: bug
