### ISSUE TITLE
[Request] Review Fanart arts collections.

### ISSUE THREAD

**Issue by matke-84** [elgatito/plugin.video.elementum#637] opened 2020-11-10 20:20 UTC
As the title says. When I use the default fanart I don't get a clearlogo on any of the skins. When I turn on fanart.tv I get everything but everything is very slow and to be honest I get weird backgrounds, instead of backgrounds it is often clearart so it looks weird, then I get weird clearlogos ... Is there a possibility to get complete support with default fanart for posters and images (clearlogos, cleararts...). I know there is no more support for the element but I would be very grateful if you could fix this. Thanks in advance.

**Comment by elgatito** [comment] 2020-11-11 13:20
@matke-84 If you think there are arts on TMDB, which you don't see through Elementum - provide exact TMDB item, so it can be inspected.

**Comment by matke-84** [comment] 2020-11-11 14:20
Sorry maybe I wasn't clear. With the default element settings I don't get a clearlogs. 
![default settings](https://user-images.githubusercontent.com/74268331/98820780-e8eeed00-242e-11eb-91e7-6b951bb27dad.png)
![no clearlogos](https://user-images.githubusercontent.com/74268331/98820838-0328cb00-242f-11eb-8bfe-2633e2f2ac65.png)
When I turn on use fanart.tv I get everything but with this setting it's slower loading. Secondly, I get for a lot of movies instead of a background cleaart and it looks very weird then.
![fanart tv](https://user-images.githubusercontent.com/74268331/98821162-70d4f700-242f-11eb-955c-de475e034fca.png)
![with clearlogo](https://user-images.githubusercontent.com/74268331/98821194-821e0380-242f-11eb-85b0-746c812bd290.png)
This all happens with all skins that support fanart clearlogos. I also contacted some skin creators and people from fanart.tv and they all told me that the problem is with the elementum, supposedly something needs to be sorted out to get full support, elementum api problem or something like that. Sorry for the longer post but I don't know how else to explain.

**Comment by elgatito** [comment] 2020-11-11 14:25
@matke-84 As I've said before, please, provide an item which has arts on TMDB website, and you don't see that arts in Kodi/Elementum.

https://www.themoviedb.org/

**Comment by matke-84** [comment] 2020-11-11 15:49
Sorry but we don't seem to understand each other. There are no clearlogos (movies title logos) on tmdb. Not a problem with posters and backgrounds. Please look carefully at the pictures. Clearlogos only exist on fanart.tv as i know. 
![clearlogo title](https://user-images.githubusercontent.com/74268331/98832506-32decf80-243d-11eb-8e13-275d6d9b6fc6.png)
It needs to set to pull posters and wallpapers from tmdb for movies and tvdb for tv shows and everything else from fanart.tv. This was done by some other similar addons. Or at least if you can set that when you turn on use fanart.tv option pulls the background properly and not clearart. It looks ugly like this.
![wrong background](https://user-images.githubusercontent.com/74268331/98830899-37a28400-243b-11eb-8e82-59346c766824.png)
I got this in response when I asked a question on fanart.tv about incorrect background views.
![Screenshot_20201111-162452](https://user-images.githubusercontent.com/74268331/98831000-50ab3500-243b-11eb-91ac-a9146da593b8.jpg)
It would be really nice if this could be sorted out. Many would be grateful to you for this. Thanks in advance. If you need any help, I'm here.

**Comment by elgatito** [comment] 2020-11-11 16:05
@matke-84 

> Sorry but we don't seem to understand each other. 

You are right. I don't understand what you want.
You say there are not clear arts, then you say it is wrong, then you say it is on fanart, but you don't like it, then you say it should be fanart. I do not understand.

**Comment by elgatito** [comment] 2020-11-11 16:06
That is why I asked two times to provide a sample of an item on TMDB, where you show that "this art should there and there", so that it is clear what should be where.

**Comment by matke-84** [comment] 2020-11-11 16:43
Sorry but I really don't know how else to explain.
You don't have a clearlogo on tmdb, so I don't know what to show you. But I can show you on fanart.tv. For example on the movie the godfather:
I want clearlogos on every movie:
![Screenshot_20201111-171431](https://user-images.githubusercontent.com/74268331/98836561-1d1fd900-2442-11eb-8463-01ec36abe93e.jpg)
Instead of this clearart:
![Screenshot_20201111-171458](https://user-images.githubusercontent.com/74268331/98836719-4e98a480-2442-11eb-8e07-901bc128f867.jpg)
I want it to be the background
![Screenshot_20201111-171534](https://user-images.githubusercontent.com/74268331/98836907-928ba980-2442-11eb-9eb3-2f12a0fe8c34.jpg)
This is how it looks like when the option "use fanart.tv for poster/images" is not turned on. This is default setings in elementum. 
![no clearlogo](https://user-images.githubusercontent.com/74268331/98837904-d59a4c80-2443-11eb-8739-4b20e7a88c39.png)
As you can see there are posters and backgrounds but no clearlog.
This is how it looks like when the mentioned option is turned on.
![clearlogo and back](https://user-images.githubusercontent.com/74268331/98838189-3164d580-2444-11eb-81be-5f4fad1c1446.png)
As you can see a clearlogo has appeared but it is clearart instead of the background.
All of this happens in both tv shows and movies.
I can't do better than this. :-)

**Comment by elgatito** [comment] 2020-11-11 17:38
@matke-84 but why don't you enable use of fanart.tv in Elementum settings? It does not work as expected?

**Comment by matke-84** [comment] 2020-11-11 18:06
I use it, but it loads images much slower, but I can handle that. But as you stated, it doesn't work properly, more precisely, it shows posters properly, but the backgrounds for a lot of movies are not good (the Godfather, LOTR, Dark knight, Harry Potter, Back to the future......). It displays cleararts instead of backgrounds. I sent it to you in previous posts. You need to fix that. And the answer from the people from fanart.tv that I posted says the same thing.
![Screenshot_20201111-162452](https://user-images.githubusercontent.com/74268331/98847559-bbb33680-2450-11eb-9110-8e13e02c0fb3.jpg)

**Comment by elgatito** [comment] 2020-11-11 18:31
@matke-84 Here and below you can see which fields are used for each art type for Kodi:
https://github.com/elgatito/elementum/blob/master/fanart/fanart.go#L270

I don't see where we can get clearlogo for movies.
For shows/seasons/episodes we should currently use ClearArt and ClearLogo.

**Comment by matke-84** [comment] 2020-11-11 18:54
Sorry, I'm not the best at programming kodi addon. Clearlogos and cleararts for movies and tv shows we can use from https://fanart.tv/. Can we use tmdb-tvdb id in combination with fanart.tv id?

**Comment by elgatito** [comment] 2020-11-11 20:06
@matke-84 I have posted the link just to verify what data from fanart is used for what art in Kodi.

Example for movie:
```
ClearArt:  HDMovieClearArt
ClearLogo: HDMovieLogo or MovieLogo
```

I do not see ClearLogo data from Fanart, is it there?
Can you show any Movie and TVShow on Fanart, that has arts, that you want to see in Elementum?

**Comment by matke-84** [comment] 2020-11-11 21:04
For example The Dark knight.
https://fanart.tv/movie/155/the-dark-knight/
Clearlogo (also clearart) is no longer used for newer titles, now there is hdclearlogo (hdclearart) . But you can add in code for any case if not exist hdclearlogo to use clearlogo.
![Screenshot_20201111-213736](https://user-images.githubusercontent.com/74268331/98862159-b9f46d80-2466-11eb-8710-3bca13e75922.jpg)
Posters are not a problem, so far they have been ok.
![Screenshot_20201111-214227](https://user-images.githubusercontent.com/74268331/98862300-f4f6a100-2466-11eb-9bdc-faf38caa590a.jpg)
Now, it is important to fix this, so that the movie background be a background, not clearart, it has a different role.
![Screenshot_20201111-214734](https://user-images.githubusercontent.com/74268331/98862645-8b2ac700-2467-11eb-89c1-ec747cd29c02.jpg)
Purely as additional information, there is also a cdart and banners used by some skins, so if you want you can insert it into the code.
![Screenshot_20201111-215214](https://user-images.githubusercontent.com/74268331/98863129-33409000-2468-11eb-9454-0490d20db07b.jpg)
![Screenshot_20201111-220014](https://user-images.githubusercontent.com/74268331/98863881-50c22980-2469-11eb-8b93-8f9aae43ccaf.jpg)
If there's anything I can do to help you, test or whatever, I'm here.

**Comment by matke-84** [comment] 2020-11-12 14:54
Here are the links if it's easier:
HDCLEARLOGO(hdmovielogo)-https://fanart.tv/fanart/movies/155/hdmovielogo/the-dark-knight-507b2081e02dd.png
POSTER(movieposter)-https://fanart.tv/fanart/movies/155/movieposter/the-dark-knight-551465d577af5.jpg
BACKGROUND(moviebackground)-https://fanart.tv/fanart/movies/155/moviebackground/the-dark-knight-58fa275637ae0.jpg
If you need the rest (HDCLEARLOGO,CDART,BANNER,MOVIE THUMBS...) I can leave links for that too.

**Comment by elgatito** [comment] 2020-11-13 14:04
@matke-84 there is no "ClearLogo" in Fanart for movies. There is only "ClearArt". 
Kodi has fields for both ClearLogo and ClearArt. 
Currently we pass ClearArt as it is. 
For ClearLogo we pass HDMovieLogo.

**Comment by matke-84** [comment] 2020-11-13 15:49
Ok, I figured it out too in the end as you can see from my previous post. :-) Is there anything that can be done to fix these issues from all previous posts?

**Comment by elgatito** [comment] 2020-11-13 16:00
@matke-84 I have no idea what you want to fix and don't have time to sort everything.
If you say "this field in Kodi Art should be set with this field from Fanart" - I can do that.
As I said, you can see what fields in Kodi are set from Fanart.

**Comment by JacopoV** [comment] 2020-11-18 08:13
@elgatito Hi, i do have a similar issue, and i ve been able to isolate the issue to be related with some recent elemetum updates (at least it seems ). I had to install a 2/3 weeks backup  for kodi and i notice far art was loaded correctly, then updated to the last version but they don't show up anymore, even tho the option are checked. If i provide both logs, both pictures and both instrtuctions,  you want to  me log the bug here or in a new one ? Many  thanks

**Comment by elgatito** [comment] 2020-11-18 11:53
@JacopoV you should be more clear what does not work for you and where. I do not understand what you write about.

**Comment by JacopoV** [comment] 2020-11-18 12:12
@elgatito i apologise if i haven't been clear enough. So before opening a ticket i ve looked into if someone else was having the  same issue i do have. And this one seems pretty similar, due the fact that has something to do with clearart  and clearlogo ( i think). 
So the issue  is :  in Elemetum settings i've  both "Use default fan art " and " Use fanart.tv for poster/images" on . With these 2 options turned on, in Aura UI, in landscape widgets i get the correct background and the logo overlapping nicely. 
If i do turn off these 2 settings i mentioned in Elemetum, in the landscape widget the background stays and the logo goes away. 
In Elementum 0.1.59 it still works like that, so both settings on and i ve no issues  at all. 
In Elementum 0.1.62 , even both settings are turned on, i get only the background and not the logo.

I do have logs, all pics etc if you think you have the time to look into, it it's an issue with elementum.
As stated before, this  behaviour happens only  if  i update Elementum. 
I can stick with 0.1.59 but  i like to get  the latest updates, especially to solve Trakt issue, for  their sake considering they requested changes.

**Comment by elgatito** [comment] 2020-11-18 12:22
> With these 2 options turned on, in Aura UI, in landscape widgets i get the correct background and the logo overlapping nicely.
> If i do turn off these 2 settings i mentioned in Elemetum, in the landscape widget the background stays and the logo goes away.

You are talking about logo only? Lists of items or when you start playback of some item?
Would be good if you share which movie/show/season/episode you look at, show a screenshot where arts look fine, and screenshot where it is not good.

**Comment by JacopoV** [comment] 2020-11-18 12:24
@elgatito yeah just the logo in the UI, before playing. Ok i ll give you everything i got, gimme a  bit to format a post so i can make your life easier and be more helpful :)

**Comment by JacopoV** [comment] 2020-11-18 12:39
@elgatito  So here we are. Both Elementum having "Use default fan art " and " Use fanart.tv for poster/images" turned ON for 0.1.59 and 0.1.62 .

**Focus area** : look at the widgets in the second row, like True Detective , Money Heist and Dark, which are Trakt in progress list if it does matter.

**About updates** : once i push back in my Kodi backup, there are 2 addons they wants to be updated : Elementum, Burst for Elementum. Burst is not causing any issue, so due my testing, the issues shows up when i apply the update for Elementum from 0.1.59 to 0.1.62 . Between the tests and debug, i always fully reboot Kodi.

**Elementum 0.1.59**
How it looks : 
![0 1 59](https://user-images.githubusercontent.com/1202954/99530529-b77f9f80-29a1-11eb-82e5-4aae37e6170b.jpg)

As you can see the logo ( in this case the show title) is displayed on top the background  as still image from the episode.
LOG  for 0.1.59 before updating  : https://paste.kodi.tv/datacudozu


**Elementum 0.1.62**
How it looks : 
![0 1 62](https://user-images.githubusercontent.com/1202954/99531102-8358ae80-29a2-11eb-9a0a-95c3e8cbe7c6.jpg)


As you can see the logo that was displayed on top the background as still image from the episode, it's not visible anymore.
LOG  for 0.1.62 after being updated  : http://paste.kodi.tv/binohuvuge

Let me know if i can help you proving more info  or running more test. I can easily revert back to my backup before  the update. 
Thanks for your  time

**Comment by elgatito** [comment] 2020-11-18 12:55
@JacopoV Do you see the same with movies? Upper row is not from Elementum, so other arts are used?

Let's take a look at Dark arts.
TMDB: https://www.themoviedb.org/tv/70523-dark/images/backdrops
Fanart: https://fanart.tv/series/334824/dark/

Fields, taken by Kodi:
```
thumb
poster
banner
fanart
clearart
clearlogo
landscape
icon
```

We need to review where should each item go to.
Difference between 0.1.59 and 0.1.62, when using Fanart, is that we don't take usual Logo for ClearLogo arts.
https://github.com/elgatito/elementum/commit/7492b22e4f5d2d440f41d093bdc047c05c36290a

**Comment by JacopoV** [comment] 2020-11-18 13:07
@elgatito first thanks for the quick look. 

Regarding your question (very valid one) it seems to be more spread on TV shows , sometimes on movies if they work in the  same way. I thought it was because they were too recent or something like it.
The upper row, in TV Show section, is still Trakt.  It's the collection in my account. 

I made a short video in here to show you more.  Maybe you spot something more than i do : 
https://gofile.io/d/8rLkJY

**Comment by matke-84** [comment] 2020-11-18 17:33
OK. I noticed one more thing. If I turn on the option in elementum to pull data from trakt then neither clearlogo nor clearart appears anymore. I still think something is not right here. For example in tmdb helper it does everything properly with trakt lists. Don't get me wrong, I love so much this addon and I have great respect for you and your work, I'm just trying to make it as good as possible.

**Comment by elgatito** [comment] 2020-11-19 10:42
@matke-84 If you enable to use Trakt information, it means Trakt items are not overwritten with TMDB information and images. It will not help with images, at all.

**Comment by JacopoV** [comment] 2020-11-19 11:02
@elgatito regarding "my issue" is there something i can do to fix it  ? about this change elgatito/elementum@7492b22 ? thanks

**Comment by JacopoV** [comment] 2020-11-30 15:27
As workaround I rolled back to Elememtum 0.1.59 for now. Hopefully in the future releases can be fixed, if you have time @elgatito. Thanks for your precious time.

**Comment by matke-84** [comment] 2020-12-10 20:07
@elgatito There is something wrong with the latest version. It has a problem to pull movies or tv show logos especially for tv shows. For example Stranger Things, Flash... It works with version 0.1.61.

**Comment by elgatito** [comment] 2020-12-10 20:12
@JacopoV @matke-84 which skins you use on your screenshots?

**Comment by matke-84** [comment] 2020-12-10 20:18
Titan bingie mod, and for movie Superintelligence i got russian logo.

**Comment by matke-84** [comment] 2020-12-10 20:28
And I found something else very interesting. TMDB helper also takes pictures, logos ... from fanart.tv but he doesn't have the problems we wrote about here and somehow everything looks cleaner. Could changing or updating fanart.tv api key be a solution?

**Comment by elgatito** [comment] 2020-12-12 15:49
@JacopoV How can I make same view as you have with your skin? I guess it is default Aura skin? How to make big images with clear logos?

**Comment by JacopoV** [comment] 2020-12-12 15:58
@elgatito Hey Denis, sorry, i'never received any notifications about this thread till this last tag. Thanks for looking into.

Yeah it's normal Aura. The best way to have the layout showing the  issue, is to go to  : 
- Settings  > Skin Settings > Customise Home Menu
- Add Widget >  browse and add using Elementum Trakt Progress 
- Then set the widget to be landscape

Options that are needed to see background + logo  ( working in 0.1.59 ) are  : 
- Elementum  : "Use default fan art " and " Use fanart.tv for poster/images" both ON
- Aura : Settings  > Skin Settings > Home > " Prefer Fanart for landscape widgets " ON

It should be enough. 
Let me know please if you're able to reproduce it, otherwise i can make a video with a passthru of all the settings i have.
Many thanks

**Comment by elgatito** [comment] 2020-12-12 17:21
@JacopoV Could finally find the place to see logo over the landscape, thanks.

**Comment by JacopoV** [comment] 2020-12-12 17:23
No worries, thanks to you @elgatito. Any idea if could be fixed in a future release? I m still on 0.1.59 because of that.

Cheers

**Comment by matke-84** [comment] 2020-12-19 10:48
> @elgatito There is something wrong with the latest version. It has a problem to pull movies or tv show logos especially for tv shows. For example Stranger Things, Flash... It works with version 0.1.61.

@elgatito Is there a chance to fix this problem with the latest version of the elementum?

**Comment by JacopoV** [comment] 2020-12-20 19:23
@matke-84 I think we have the same issue. I'm using elementum 0.1.59, but in 0.1.62 a change has been done about it. So we are both affected..

**Comment by matke-84** [comment] 2020-12-21 19:45
@JacopoV It seems to me. All we have to do is wait for @elgatito sort it out.

**Comment by elgatito** [comment] 2020-12-22 10:27
@JacopoV @matke-84 Please, try with v0.1.63.

**Comment by matke-84** [comment] 2020-12-22 22:03
@elgatito Omg, you managed to fix the fanarts. I've been telling you about this all time. Now it shows everything much better. There are still some things that tmdb helper shows me and elementum doesn't but I will check it again and let you know. Is there a chance to insert MPAA ratings for movies and tv shows? It would be awesome.

**Comment by elgatito** [comment] 2020-12-23 13:00
@matke-84 I have tried to add MPAA where possible to movies/shows. But it's not everywhere there.
Please, try with 0.1.64.

**Comment by matke-84** [comment] 2020-12-23 13:52
@elgatito I can't find version 0.1.64.

**Comment by matke-84** [comment] 2020-12-23 14:08
@elgatito My mistake. Found. I'll try.

**Comment by elgatito** [comment] 2020-12-23 14:16
@matke-84 It was a delay with release upload. Now finishing just items.

**Comment by matke-84** [comment] 2020-12-23 14:34
@elgatito I don't get an MPAA. Do I need to do something special?

**Comment by elgatito** [comment] 2020-12-23 14:38
@matke-84 Try to "Clear TMDB cache", in Elementum settings.

**Comment by matke-84** [comment] 2020-12-23 15:38
Nope , I tried everything but nothing. It works in tmdb helper.

![elementum vs tmdb helper](https://user-images.githubusercontent.com/74268331/103013310-376acd80-453d-11eb-85f2-75ccc3266f67.jpg)

**Comment by matke-84** [comment] 2020-12-23 15:55
@elgatito There is also a lack of pictures here. I'm trying to find a solution to the problem today, but I'm not doing well. Elementum does not find an image. In TMDB helper appears. Can you help me where to look.

![missing picture](https://user-images.githubusercontent.com/74268331/103014305-dc39da80-453e-11eb-9c7c-3de16b20f17b.jpg)

Titan bingie mod skin part of code which I suspect is in charge of this.

`
			<control type="image">
				<visible>String.Contains(Control.GetLabel(12345),landscape)</visible>
				<visible>yes</visible>
				<top>20</top>
				<left>15</left>
				<width>570</width>
				<height>350</height>
				
				<aspectratio aligny="center" align="left">keep</aspectratio>
				<include condition="!String.Contains(Skin.String(SkinHelper.StudioLogos.Path),colo)">videoInfoColorDiffuse</include>
				<texture background="true">$VAR[View525SeasonOrShowLandscape]</texture>
			</control>`

**Comment by elgatito** [comment] 2020-12-23 16:53
> Nope , I tried everything but nothing. It works in tmdb helper.

Now I see, I was matching by language, and it has mpaa per-country, changed that.

> There is also a lack of pictures here. I'm trying to find a solution to the problem today, but I'm not doing well. Elementum does not find an image. In TMDB helper appears. Can you help me where to look.

**Comment by matke-84** [comment] 2020-12-23 17:09
@elgatito As in Elementum, the option to download from fanart.tv must be enabled. And one more thing. In TMDB Helper go to the trakt list, not the tmdb list. Only then displays all information.

![tmdb](https://user-images.githubusercontent.com/74268331/103021045-ced61d80-4549-11eb-8524-d6368b911c95.jpg)

**Comment by JacopoV** [comment] 2020-12-23 21:57
@elgatito 0.1.64 works great! Really really thank you.
Even tho development for Elememtum has been stopped, I do really appreciate your time still invested. I ll take the opportunity to wish you Merry Christmas. 
Deeply, thanks again.

**Comment by matke-84** [comment] 2020-12-24 13:35
Hi @elgatito. Did you manage to get the MPAA? Also I was trying yesterday to find out where the skin was pulling that image from and I failed. In the skin, I manage to change the picture of the episode to appear, but not the picture of the whole TV Show or season, as in TMDB helper or the local movie library. This line of code in titan bingie mod is charge of that. 
`<texture background="true">$VAR[View525SeasonOrShowLandscape]</texture>`
Did you have time to look? Thanks in advance.

![episode view](https://user-images.githubusercontent.com/74268331/103091154-8a9f5780-45f3-11eb-91d4-89c5fcb2522f.jpg)

**Comment by elgatito** [comment] 2020-12-24 16:29
@matke-84 
> Did you manage to get the MPAA? 
Yes, with 0.1.64, if there is certification for my region, I get proper MPAA.

> Did you have time to look?

No. Each skin has own login on selecting arts. If you find any information, which one is missed - you can write about it. 
I don't know what it wants with the latest version of Elementum.

**Comment by matke-84** [comment] 2020-12-24 17:05
> Now I see, I was matching by language, and it has mpaa per-country, changed that.

> Did you manage to get the MPAA?
   Yes, with 0.1.64, if there is certification for my region, I get proper MPAA.

@elgatito Sorry, I don't think I understood you the best. Why can't I get MPAA? I changed regions, US, UK.. but I still don’t get it. In TMDB Helper works.

**Comment by elgatito** [comment] 2020-12-24 19:55
@matke-84 I have no idea. Try to clean TMDB/Trakt cache in Elementum. 

Closing this issue. Because it's about fanarts.

**Closed by elgatito** 2020-12-24 19:55 UTC
Labels: enhancement

**Comment by matke-84** [comment] 2020-12-24 20:21
@elgatito Just please tell me does it works for you in titan bingie mode? And I don't know what you means "Now I see, I was matching by language, and it has mpaa per-country, changed that." Where should I change this?

**Comment by matke-84** [comment] 2020-12-25 00:20
@elgatito There is definitely something wrong with MPAA. I tried some other skins and it doesn't work. Installed kodi from scratch, reinstalled everything and nothing. Maybe this will help you. When I turn on the option in the elementum "Use Trakt Information in Trakt lists" MPAA displays without any problems, of course everything else is lost. But look at how you set up the MPAA for the trakt so maybe that's the solution for the problem. MPAA is the basic information, as well as the duration, realise date... it should not cause so many problems. I would be very grateful if you could solve this problem. Thanks in advance. Happy Holidays. :-)
