### ISSUE TITLE
UTP bandwidth management - Slow speeds over VPN

### ISSUE THREAD

**Issue by jasjeet** [elgatito/plugin.video.elementum#450] opened 2019-06-15 11:27 UTC
Latest version of elementum 0.1.35 installed on Kodi 18.2

**Setup as follows:**
OpenVPN client on Windows 10 PC/OpenVPN client on Netgear R7800 DDWRT firmware (same behavior on both).

100Mbps internet connection, over VPN it tests around 65mbps at speedtest.net, Windows 10 or Router as client.

In Elementum, speeds are limited around 1.4/1.5MBps or lower, but generally settle exactly here.
In Utorrent 2.2.1, the same is observed. Speeds are capped around 1.4/1.5MB/s. Until unchecking
 `Enable bandwidth management [UTP]`. Then speeds are going to 6.5MB/s.
I found this solution here, it is well known it seems, some issue with UTP traffic getting throttled over VPN connections.
[PIA VPN Slow Torrents](https://www.privateinternetaccess.com/forum/discussion/23112/anyone-having-torrent-slowdowns-please-read-this)

In my case, I run my own VPS, which runs OpenVPN Server, but the above guidance solved my issue in UTorrent.

I do not see any way to change this behavior in libtorrent via the Elementum Settings or libtorrent.config that is referenced.

Disabling UTP in Elementum doesnt help, the speeds still seem capped around 1.4MBps - I am not certain this settings is working as expected, as I cannot test this in UTorrent 2.2.1.

I notice in Utorrent that the number of requests being made to peers is much higher, in order of 3-4x when the bandwidth management is disabled for UTP.

Another observation, since this is forked from Quasar - In Quasar i used to get my entire bandwidth, at the time it was 30mbps (only upgraded to 100Mb last week). Now in recent months I struggled with Quasar, always capping out at 1.3-1.4MBps too. I thought it was bad torrents, till i ruled it out. That is what made me test Elementum, and it is having the same behavior.
Something has changed here causing the slowdown over VPN. My entire environment is locked down for over 1 year. The HTPC which prompted to start testing on my Win 10 PC is not touched for many years, and the Router Client VPN Config is also untouched for years since i set it up initially.

## Expected Behavior
I'm expecting to get the full 6.5MBps my VPN can deliver.
The test torrent is the Ubuntu ISO from the Ubuntu website, which consistently delivers 6.5MBps in Utorrent instantly once I uncheck "Enable bandwidth management [UTP]"

## Current Behavior
Speeds over OpenVPN are being limited to around 1.4MBps

## Possible Solution
Some sort of bandwidth throttling on the UTP side needs looking at.
One workaround is setting a connection limit that is very low, eg 5. This prevents huge number of peers and requests, so you don't hit the throttling and then if these few peers have high bandwidth, you can max out the connection.

## Steps to Reproduce (for bugs)
1. Use a VPN like PIA, or setup an OpenVPN server. Connect Win 10 client to VPN.
2. My OVPN settings
```
client
proto udp
remote <IP>
port 1194
dev tun
nobind
tls-client
key-direction 1
cipher AES-128-CBC
comp-lzo
auth sha256
```

3. Try to download Ubuntu torrent in Kodi or via Web UI of Elementum

# Your Environment
Elementum 0.1.35
Windows 10 build 17134.829
Kodi 18.2

* Link to Kodi debug log:
debug/all log while downloading 
https://pastebin.com/XFJXA5UK

debug/bundle after i cancelled download after around 1 minute
https://1drv.ms/u/s!Ajkm_rI8_Wi2lCigojZv1y_n2MUx?e=0umLro

**Comment by jasjeet** [comment] 2019-06-15 14:03
Something else i notice. If `Enable bandwidth management [UTP]` is enabled in UTorrent and my download is less than 1MB/s - just like i see in Elementum, and I run a speedtest simultaneously - The speedtest is also only giving back 10mbps. Meaning, something here in the torrent library might be destroying the connection itself causing the entire pipe to be congested. Soon as I stop the torrent, i see 65Mb/s at speedtest.net again.

**Comment by jasjeet** [comment] 2019-06-15 19:36
Workaround that fixed this all, switch the VPN from UDP to TCP. I even seem to get better speeds, Ubuntu downloading at 7.8MBps on a 100mbps line. Basically maxing out my VPN Servers CPU.

**Comment by antonsoroko** [comment] 2019-06-15 19:52
Thanks for sharing this info.
I also have slower speed in elementum in comparison to transmission (for example) on android TV with openvpn in TCP mode.

**Comment by jasjeetsuri** [comment] 2019-06-15 20:28
TCP for OpenVPN is supposedly slower in overall throughout, but 70mbps is enough for me. In fact on a Speedtest it’s giving me around 4mbps more than UDP likely because of the VPS CPU bottleneck, TCP is probably lighter.

Having OpenVPN using UDP, the throughout is just terrible no matter what combination of settings I tried. It fixed Quasars throughput too.

I hope others find this useful.

**Comment by elgatito** [comment] 2019-07-29 18:42
You should try WireGuard on your router, if you have possibility from VPN provider.
It can easily download 200mbit on Xiaomi 3G router.

There is nothing to do with addon, you can disable UTP if it creates big load on your router.

**Comment by jasjeetsuri** [comment] 2019-07-29 18:45
My Router is an R7800 running DDWRT firmware. And I don’t use a public VPN, I own a VPS that I run OpenVPN server on in another country. I could swap OpenVPN server for WireGuard, but why is it better and how would it help?

**Comment by elgatito** [comment] 2019-07-29 19:28
@jasjeetsuri it is usually faster and makes lower cpu usage.

**Comment by elgatito** [comment] 2019-08-21 10:49
Closing as the issue is probably connected to libtorrent work or local network devices.

**Closed by elgatito** 2019-08-21 10:49 UTC
