### ISSUE TITLE
Doesn't show results when one of the providers is failed

### ISSUE THREAD

**Issue by burekas7** [elgatito/plugin.video.elementum#414] opened 2019-04-13 11:29 UTC
* I don't know if it's a burst or elementum issue.

Sometime when running a search and one provider is failed, it shows "No links found" while the other providers are well and return results as it shows in the kodi log:
https://paste.ubuntu.com/p/TJQtmnHqC4

Elementum 0.1.25
Kodi 17.6
Windows 10, 64bit

**Comment by elgatito** [comment] 2019-04-13 12:13
Try to increase timeout in Burst. It looks like connection is closed by burst plugin.

**Comment by burekas7** [comment] 2019-04-13 12:22
My "custom provider timeout" is enabled and set for 22 seconds.
But the issue is it finished the searching process less then 15 seconds, so it's not the problem I think.
But even if there is timeout I think it should be able to show the other results that was return from the other providers instead of failing the all process and tell that "No links found".

**Comment by KillerJoeBR** [comment] 2019-04-13 18:37
This issue is something that always existed since quasar. If one provider is slow or offline then you won't get any results because of the time out.

You should in elementum set the timeout like 30 seconds and in burst set the timeout like 15 seconds or something. The important thing is that burst timeout is sooner than the elementum, not the opposite.

**Comment by KillerJoeBR** [comment] 2019-04-13 18:38
But I agree that it would be better if elementum could get the results either way. But like I said it has been the same since quasar

**Comment by burekas7** [comment] 2019-04-13 19:44
@KillerJoeBR 

Yes, I know. It's an old issue since quasar, but I think this issue was opened here in the past and I think that was fixed. But now it seems to happen more.
Sometimes it gets over it and sometimes it fails all the rest of the results because one or more problematic provider.

My timeouts are bigger then the "No links found" is shown. So I think it's not a timeout issue.
But as you said it should be fixed so even some of the providers are bad, the other results will be shown.

**Comment by burekas7** [comment] 2019-04-13 19:47
@KillerJoeBR 

By the way, where do you see 2 different timeouts?
There is only "Custome provider timeout" under "Providers" tab.

**Comment by KillerJoeBR** [comment] 2019-04-13 20:05
In elementum that is the setting you need to change.

In burst there is an option setting like set the timeout according to elementum or something like that. You need to mark it and then you will get the option to set a timeout manually. I usually set it like 12 seconds.

**Comment by burekas7** [comment] 2019-04-13 20:15
Basically you should disable it and then the option for setting timeout is shown.
(When it's enabled it means "Automatically adjust timeout according to Elementum settings")

Hope it will help a little. Thanks.

**Comment by KillerJoeBR** [comment] 2019-04-13 20:27
I'm doing this by memory so I can be wrong. I said you need to mark it, but maybe you need to unmark it

**Comment by elgatito** [comment] 2019-04-19 18:58
I cannot reproduce this issue. Every time when one provider fails - I get results from other providers.

By default, Burst is getting timeout from Elementum settings and not letting burst timeout to be greater than Elementum's.

**Comment by elgatito** [comment] 2019-04-19 18:59
> Basically you should disable it and then the option for setting timeout is shown.

With Disabled option - it can surely fail, because it cannot finish in time.

**Comment by elgatito** [comment] 2019-04-25 20:01
I cannot reproduce this bug. 
Make sure you have enabled using timeout according to Elementum (in Burst settings). It will make sure Burst's timeout is less then Elementum so if any provider can't finish in time - it will stop and return others.

**Closed by elgatito** 2019-04-25 20:01 UTC
