### ISSUE TITLE
Cannot get installed on Vero 4K

### ISSUE THREAD

**Issue by mrromanticao** [elgatito/plugin.video.elementum#136] opened 2018-04-06 00:25 UTC
Hello,

Been trying to install Elementum on my Vero 4k and cannot get it to work. Have tried the recommendations on the 2 closed issues but still not working. 
Even after trying sudo to install arm64bit will not work.
Tried installing with the big file and when I try to open Elementum, it gives error "could not find binary for architecture "linux_arm64""!

Please help.

**Comment by elgatito** [comment] 2018-04-11 10:37
You will get no help without proper kodi.log.
http://kodi.wiki/view/Log_file/Easy

**Comment by elgatito** [comment] 2018-04-20 13:34
I will close the issue if there is no information provided.

**Closed** 2018-04-26 20:00 UTC

**Comment by yazun** [comment] 2019-02-17 18:52
Can confirm the issue, probably duplicate of https://github.com/scakemyer/plugin.video.quasar/issues/810
vero 4K reports os a "arm" 
```

19:39:24.784 T:3739218688  NOTICE: [plugin.video.elementum] Python version: ['2.7.13 (default, Sep 26 2018, 18:42:22) ', '[GCC 6.3.0 20170516]']
                                                dist: ('debian', '9.6', '')
                                                linux_distribution: ('debian', '9.6', '')
                                                system: Linux
                                                machine: arm
                                                platform: Linux-3.14.29-134-osmc-arm-with-debian-9.6
                                                uname: ('Linux', 'blacha', '3.14.29-134-osmc', '#1 SMP Mon Dec 31 00:16:36 UTC 2018', 'arm', '')
                                                version: #1 SMP Mon Dec 31 00:16:36 UTC 2018
                                                mac_ver: ('', ('', '', ''), '')
19:39:24.785 T:3739218688  NOTICE: [plugin.video.elementum] CPU: proc0={'CPU implementer': '0x41', 'Features': 'fp asimd evtstrm aes pmull sha1 sha2 crc32 wp half thumb fastmult vfp edsp neon vfpv3 tlsi vfpv4 idiva idivt', 'CPU architecture': '8', 'processor': '3', 'Hardware': 'Vero4K', 'CPU revision': '4', 'CPU part': '0xd03', 'Serial': '210a82005cd990926a8688a4c1ba22f2', 'Processor': 'AArch64 Processor rev 4 (aarch64)', 'CPU variant': '0x0'}
19:39:24.786 T:3739218688  NOTICE: [plugin.video.elementum] Exploring model: aarch64 processor rev 4 (aarch64)
19:39:24.786 T:3739218688  NOTICE: [plugin.video.elementum] Using CPU info arch: arm64
19:39:25.103 T:3391091456  NOTICE: [plugin.video.elementum] elementumd: starting elementumd
19:39:25.108 T:3399480064  NOTICE: [plugin.video.elementum] elementum: starting jsonrpc service
19:39:25.136 T:3391091456  NOTICE: [plugin.video.elementum] Kodi's JSON-RPC service is available, starting up...
19:39:25.176 T:3391091456  NOTICE: [plugin.video.elementum] Binary detection. Source: /home/osmc/.kodi/addons/plugin.video.elementum/resources/bin/linux_arm64/elementum, Destination: /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum
19:39:27.917 T:3808424704  NOTICE: script.tv.show.next.aired --> TV Show - Next Aired version 7.0.1 started
19:39:29.928 T:3755995904  NOTICE: Start - EPG thread started
19:39:35.651 T:3391091456  NOTICE: [plugin.video.elementum] Deleting stale files set([])
19:39:35.651 T:3391091456  NOTICE: [plugin.video.elementum] Binary detection: [ Source: /home/osmc/.kodi/addons/plugin.video.elementum/resources/bin/linux_arm64/elementum, Destination: /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum ]
19:39:35.652 T:3391091456  NOTICE: [plugin.video.elementum] Binary dir: /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64, item: /home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum
19:39:35.695 T:3391091456  NOTICE: [plugin.video.elementum] elementumd: start args: [u'/home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64/elementum'], kw: {'close_fds': True, 'env': {'USERNAME': 'osmc', 'SUDO_COMMAND': '/usr/lib/kodi/kodi.bin --standalone -fs --lircdev /var/run/lirc/lircd', 'TERM': 'linux', 'SHELL': '/bin/bash', 'TZ': ':Europe/Warsaw', 'HOME': '/home/osmc', 'SUDO_UID': '0', 'SUDO_GID': '0', 'LD_LIBRARY_PATH': u'/home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64:', 'KODI_BIN_HOME': '/usr/lib/kodi', 'LOGNAME': 'osmc', 'USER': 'osmc', 'KODI_HOME': '/usr/share/kodi', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'MAIL': '/var/mail/osmc', 'SUDO_USER': 'root', 'OS': 'Linux', 'PYTHONOPTIMIZE': '1'}, 'cwd': u'/home/osmc/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_arm64', 'stderr': -2, 'stdout': -1}
19:39:37.057 T:3342856960  NOTICE: script.tv.show.next.aired --> Updating TheTVDB info for all continuing Kodi tv shows...
19:39:37.436 T:3391091456   ERROR: [plugin.video.elementum] Traceback (most recent call last):
19:39:37.437 T:3391091456   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 274, in elementumd_thread
19:39:37.443 T:3391091456   ERROR: [plugin.video.elementum]     proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
19:39:37.443 T:3391091456   ERROR: [plugin.video.elementum]   File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 248, in start_elementumd
19:39:37.444 T:3391091456   ERROR: [plugin.video.elementum]     return subprocess.Popen(args, **kwargs)
19:39:37.444 T:3391091456   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
19:39:37.444 T:3391091456   ERROR: [plugin.video.elementum]     errread, errwrite)
19:39:37.445 T:3391091456   ERROR: [plugin.video.elementum]   File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
19:39:37.445 T:3391091456   ERROR: [plugin.video.elementum]     raise child_exception
19:39:37.447 T:3391091456   ERROR: [plugin.video.elementum] OSError: [Errno 2] No such file or directory
19:39:37.448 T:3391091456   ERROR: [plugin.video.elementum]
19:39:37.455 T:3391091456   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 274, in elementumd_thread
                                                proc = start_elementumd(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/home/osmc/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/daemon.py", line 248, in start_elementumd
                                                return subprocess.Popen(args, **kwargs)
                                              File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
                                                errread, errwrite)
                                              File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
                                                raise child_exception
                                            OSError: [Errno 2] No such file or directory
```
