### ISSUE TITLE
Error resolving links

### ISSUE THREAD

**Issue by marcelgompact** [elgatito/plugin.video.elementum#409] opened 2019-04-05 01:25 UTC
## Expected Behavior
Elementum need to resolve links

## Current Behavior
 Elementum getting results from Burst but get an error trying to resolve them

## Possible Solution

i can get it to work if i change providers links in burst json file and then revert them it will work but only like 2hours and then error again

## Steps to Reproduce (for bugs)

1. search links for a movie 
2. no links found 
3. look at logs 
4. resolve error

## Your Environment

* Version used: 0.1.24

* Environment name and version: kodi 17 krypton, i tried kodi 18 leia too 

* Operating System and version: windows 10 x64

* Link to Kodi debug log: https://paste.kodi.tv/yoxofovuvo

**Comment by elgatito** [comment] 2019-04-13 10:10
Please try with 0.1.25.

**Comment by burekas7** [comment] 2019-04-13 11:54
I still have a problem with ygg provider:
According to the logs I have results, but the results screen doesn't show them. Why?
(It shows problem with resolving or something)

Log:
https://paste.ubuntu.com/p/mhp7yFSpT3

**Comment by marcelgompact** [comment] 2019-04-13 15:02
> 
> 
> I still have a problem with ygg provider:
> According to the logs I have results, but the results screen doesn't show them. Why?
> (It shows problem with resolving or something)
> 
> Log:
> https://paste.ubuntu.com/p/mhp7yFSpT3
> 
> Elementum 0.1.25
> Kodi 17.6
> Windows 10, 64 bit

same with 0.1.25 too

**Comment by PrevotYann** [comment] 2019-04-13 16:07
> I still have a problem with ygg provider:
> According to the logs I have results, but the results screen doesn't show them. Why?
> (It shows problem with resolving or something)
> 
> Log:
> https://paste.ubuntu.com/p/mhp7yFSpT3
> 
> Elementum 0.1.25
> Kodi 17.6
> Windows 10, 64 bit

Same with 0.1.25
Kodi 18.1
Windows 10 64bits
my log : https://pastebin.com/UDz7NJpd

**Comment by elgatito** [comment] 2019-04-13 16:30
So it's only about yggtorrent?

**Comment by PrevotYann** [comment] 2019-04-13 16:31
Yeah

**Comment by PrevotYann** [comment] 2019-04-13 16:31
> So it's only about yggtorrent?

Yeah

**Comment by chicungunya** [comment] 2019-04-14 13:01
So what's wrong @elgatito ? Is there a problem with ygg ?

**Comment by elgatito** [comment] 2019-04-14 13:02
@chicungunya probably.

**Comment by Gregsr** [comment] 2019-04-14 14:57
With 0.1.25
For Ygg, login failed (my settings are correct) and 0 result.
Log file https://paste.kodi.tv/modipowoqe.kodi

With 0.1.24
For Ygg, login successful, 15 results, error resolving link
Log file https://paste.kodi.tv/vugubuteto.kodi

kodi 18.1, win 7 64bits

**Comment by burekas7** [comment] 2019-04-14 15:02
Maybe the login is unstable but it does work in 0.1.25 also.
The problem in both version is with the resolving, see my log with 0.1.25 (I have results that return but they don't show up in the results due to the resolving error)

**Comment by elgatito** [comment] 2019-04-14 15:12
@Gregsr both your logs show same error.

**Comment by chicungunya** [comment] 2019-04-16 23:12
Hello @elgatito this is my logs : https://paste.ubuntu.com/p/DDJZV2yf68
Still no results on YGG, I really don't understand why..

Please help :)

**Comment by elgatito** [comment] 2019-04-17 18:02
Part of the problem (using IPv6 ips) will be fixed in the next version, but it does not help with yggtorrent as it is failing to download torrent files, caused by their defense.

**Closed by elgatito** 2019-04-17 18:02 UTC
