### ISSUE TITLE
Elementum crashes on startup after new install.

### ISSUE THREAD

**Issue by Quentin-Rouquette** [elgatito/plugin.video.elementum#313] opened 2018-12-24 16:52 UTC
## Expected Behavior

Elementum should be starting.
## Current Behavior

Elementum crashes after install (popup saying "Elementum has crashed, restarting..." on a loop until it gives up).
## Steps to Reproduce (for bugs)

Install elementum on Kodi.

## Context

Install elementum on Kodi.

## Your Environment

* Version used: 0.70

* Environment name and version:  Kodi 17.6

* Operating System and version:  Android TV (7.0)

* Link to Kodi debug log: http://paste.kodi.tv/baqebamuba

**Comment by chivigoku** [comment] 2018-12-25 11:12
Same problem here.
After installing version 70, it crashes.

Any solution?

thanks

**Comment by elgatito** [comment] 2018-12-25 11:59
@chivigoku no log = no help.

**Comment by elgatito** [comment] 2018-12-25 12:01
@Quentin-Rouquette log file shows it tries to start elementum multiple times. Have you updated Android or Kodi before it started to crash?

**Comment by Quentin-Rouquette** [comment] 2018-12-25 19:41
@elgatito Everything is up-to-date and it's my first time installing Elementum.

**Comment by chivigoku** [comment] 2018-12-26 17:10
hi @Quentin-Rouquette, you can resolve the issue adding a path in downloads in the settings as per #309

let us know if it works
that worked to me

**Comment by Quentin-Rouquette** [comment] 2018-12-26 21:49
@chivigoku Yup that worked, didn't think it would be that since it was set to record in RAM.

**Comment by antonsoroko** [comment] 2018-12-28 11:44
if i am not mistaken elementum still use `download directory` even if you use memory as a storage
like for some torrent related info and for downloading subtitles

maybe it should be stated more clearly in settings (or in documentation http://elementum.surge.sh/getting-started/configuration/ :-) )

**Comment by elgatito** [comment] 2019-01-01 13:18
I would be thankful if someone could provide log file if getting the issue, described here.

**Comment by elgatito** [comment] 2019-01-08 20:17
Cannot reproduce this issue even when I remove Elementum's settings with a clean install.

**Comment by elgatito** [comment] 2019-03-23 20:22
Closing, this should be fixed with latest versions.

**Closed by elgatito** 2019-03-23 20:22 UTC
