### ISSUE TITLE
Elementum causes bootloop on Rpi4 [LibreElec]

### ISSUE THREAD

**Issue by vincss** [elgatito/plugin.video.elementum#936] opened 2023-07-14 10:13 UTC
## Expected Behavior

I should be able to use elementum on a Rpi4
## Current Behavior

Elementum makes my system to reboot on initialization.
## Possible Solution

Disable elementum by deleting plugin.video.elementum inside the addon folder
## Steps to Reproduce (for bugs)

Use the latest version 0.1.92 on a Rpi 4 with libreelec.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

Rpi 4 with libreelec

Logs 

> 2023-07-14 11:36:45.196 T:1479  warning <general>: [plugin.video.elementum] Kodi's JSON-RPC service is available, starting up...
2023-07-14 11:36:45.205 T:1479  warning <general>: [plugin.video.elementum] Binary detection. Version: v0.1.92, Source: /storage/.kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum, Destination: /storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum
2023-07-14 11:36:45.207 T:1479  warning <general>: [plugin.video.elementum] Deleting stale files set()
2023-07-14 11:36:45.207 T:1479  warning <general>: [plugin.video.elementum] Binary detection: [ Source: /storage/.kodi/addons/plugin.video.elementum/resources/bin/linux_armv7/elementum, Destination: /storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum ]
2023-07-14 11:36:45.208 T:1479  warning <general>: [plugin.video.elementum] Binary dir: /storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7, item: /storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum 
2023-07-14 11:36:45.229 T:1479  warning <general>: [plugin.video.elementum] elementumd: start args: ['/storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum', '-remotePort=65221', '-localPort=65220'], kw: {'stdout': -1, 'stderr': -2, 'cwd': '/storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7', 'env': {'HISTFILESIZE': '200', 'HOSTNAME': 'ViELEC', 'SHLVL': '1', 'LD_LIBRARY_PATH': '/storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7:/usr/lib:/storage/.kodi/addons/script.module.addon.signals/lib:/storage/.kodi/addons/script.module.beautifulsoup4/lib:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.dateutil/lib:/storage/.kodi/addons/script.module.future/lib:/storage/.kodi/addons/script.module.html5lib/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.inputstreamhelper/lib:/storage/.kodi/addons/script.module.myconnpy/lib:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.six/lib:/storage/.kodi/addons/script.module.soupsieve/lib:/storage/.kodi/addons/script.module.urllib3/lib:/storage/.kodi/addons/script.module.webencodings/lib:/storage/.kodi/addons/script.yatse.kodi/lib:/storage/.kodi/addons/service.librespot/lib:/storage/.kodi/addons/virtual.system-tools/lib:/usr/lib/pulseaudio', 'HOME': '/storage', 'PS1': '\\[\\e[1;32m\\]\\h\\[\\e[1;32m\\]:\\[\\e[1;34m\\]\\w \\[\\e[0m\\]\\$ ', 'SYSTEMD_EXEC_PID': '1380', 'KODI_HOME': '/usr/share/kodi/', 'JOURNAL_STREAM': '7:12913', 'MALLOC_MMAP_THRESHOLD_': '8192', 'TERM': 'linux', 'KODI_ARGS': '', 'PATH': '/usr/bin:/usr/sbin:/storage/.kodi/addons/service.librespot/bin:/storage/.kodi/addons/virtual.multimedia-tools/bin:/storage/.kodi/addons/virtual.system-tools/bin', 'INVOCATION_ID': 'a6eb5014153e4a82a66e469d87ee8bc5', 'KODI_AE_SINK': 'ALSA+PULSE', 'LOCPATH': '/storage/.cache/locpath', 'LANG': 'C.UTF-8', 'SYSTEMD_COLORS': '0', 'KODI_TEMP': '/storage/.kodi/temp', 'PWD': '/', 'EDITOR': 'nano', 'KODI_BIN_HOME': '/usr/lib/kodi', 'OS': 'Linux', 'TZ': ':Europe/Brussels', 'LIRC_SOCKET_PATH': '/var/run/lirc/lircd', 'PYTHONOPTIMIZE': '1'}, 'close_fds': True}
2023-07-14 11:36:45.229 T:1479  warning <general>: [plugin.video.elementum] elementumd: Forcing library startup
2023-07-14 11:36:45.230 T:1479  warning <general>: [plugin.video.elementum] elementumd: loading shared library from /storage/.kodi/userdata/addon_data/plugin.video.elementum/bin/linux_armv7/elementum.so

**Comment by elgatito** [comment] 2023-07-14 14:23
Duplicate of #934 . Re-download zip file of version 0.1.92 and re-install it on top.

**Closed by elgatito** 2023-07-14 14:23 UTC
