### ISSUE TITLE
kodi 18b5 - no playback

### ISSUE THREAD

**Issue by Goga777** [elgatito/plugin.video.elementum#266] opened 2018-11-03 17:22 UTC
after the click on the name of film - in my case it is ABBA, there is kodi exit/crash. I can't play any movies with elementum from search line

## Expected Behavior

I expect that the palyback will start

## Current Behavior

after the click on the name of movie i have kodi crash/exit

## Steps to Reproduce (for bugs)

1.go to search
2.choice any item in it and click
3.wait
4.kodi will exit

## Context

i can't see anything from search

## Your Environment

* Version used:

* Environment name and version: 0.0.61
 kodi 18 beta 5/4
* Operating System and version: android nvidia shield tv 

* Link to Kodi debug log:http://slexy.org/view/s2WqiCm8o4

**Comment by elgatito** [comment] 2018-11-03 18:07
Your log does not contain useful information.
http://elementum.surge.sh/contribute/log/

**Comment by Goga777** [comment] 2018-11-04 09:06
next point - in elementum settings - on GENERAL tab - for use memory - all others options in read mode only {allow memory usage, memory size, etc}

**Comment by Goga777** [comment] 2018-11-04 09:51
here is detailed kodi.log  after reading thos page with your advices
http://slexy.org/view/s20S4dwJDC

here is the output of http://192.168.1.7:65220/debug/all just before the crash of Kodi, just before pressing the play button on ABBA MOVIE
https://slexy.org/view/s20i3uyZ9K

**Comment by vmiwouter** [comment] 2018-11-04 13:32
I got the same issue, as temporarily work around i manually relaunch kodi as administrator after that the previous crashed one shows up at the active torrent list.

**Comment by Goga777** [comment] 2018-11-04 20:37
do you have linux system?
anyway would be worth to show here is your detailed log files according to above advice

**Comment by elgatito** [comment] 2018-11-04 21:35
Kodi 18 is very buggy. I don't know why it restarts some times. There is nothing in the log.

**Comment by Goga777** [comment] 2018-11-04 22:18
did you try 18b5?
for me b4-5 quite stable

**Comment by elgatito** [comment] 2018-11-05 08:55
I can't fix something if there is no log message in Kodi and that is a problem with Kodi.

**Comment by Goga777** [comment] 2018-11-11 17:44
just to update
with kodi 18 rc1 the same issue and i don't know how to add more info in debuglog

**Comment by elgatito** [comment] 2018-11-13 08:20
I can reproduce the Kodi crash, but still Kodi is not writing any message in the log. 
So have to find it somehow.

**Comment by elgatito** [comment] 2018-11-14 19:53
Please, try with 0.0.62.

**Comment by elgatito** [comment] 2018-11-15 07:29
No, not fixed yet for every device. I will make more changes.

**Comment by compyy** [comment] 2018-11-21 12:38
works fine on Nvidia Shield now

**Comment by Goga777** [comment] 2018-11-23 18:12
today i have checked - works fine on Nvidia shield tv

**Comment by elgatito** [comment] 2018-11-23 18:59
There is another fix in 0.0.63, please try it.

**Comment by Goga777** [comment] 2018-11-24 07:48
что-то поломалос. после запуска на воспроизвдение долго крутит колесо в правом нижнем углу - waiting, потом выскакивает сообщение о том, что не удалось вопроизвести файл, а потом это сообщение пропадает и появлется окошко элементума с прогрессом буферизации, но и оно потом пропадает и снова вижу сообшение об ошибке
http://slexy.org/view/s2v6BJiwpZ

**Comment by Goga777** [comment] 2018-11-25 10:04
ситувция немного улучшилась после удаления data base в настройках элементума. Долго куртилось колесо, потом была ошибка elementum time out , а потом выскочило окно с прогрессом закачки и кино удалось посмотреть.

**Comment by elgatito** [comment] 2018-11-26 20:55
Please, try v0.0.64.

**Comment by Nuke142** [comment] 2018-11-27 09:45
Same problem here. Можно на нашем общем?
2 разных устройства - на одном Kodi 17.6, на другом дремучий spmc 16.x 
Установил ради теста Kodi на windows, Elementum 0.0.64
Всё тоже самое - отсылаю magnet-торрент при помощи HDVideoBox и YATSE - получаю постоянный круг. Ждал 5 мин и выключил.
Лог: https://pastebin.com/iQPpkv6f

**Comment by elgatito** [comment] 2018-11-27 11:55
@Nuke142 duplicate of #279 .

Здесь обсуждалаьс ошибка с зависанием и перезагрузкой Коди. Зарержка старта вызвана изменениями в торрент-библиотеке.

**Closed** 2018-11-30 11:35 UTC
